### ISSUE TITLE
Uncaught TypeError when inserting / putting from numbered register

### ISSUE THREAD

**Issue by tmunro** [t9md/atom-vim-mode-plus#1]
This problem does not occur with alphabetic registers. I think it is across all retrieval commands associated with registers.

Repro:

1. Put something into a numbered register (e.g. `"1yy`)
2. Enter insert mode
3. Insert from register in insert mode (`ctrl-r`)
4. Observe error

**Atom Version**: 1.0.11-278e988
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/vim-mode-plus) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

TypeError: Cannot read property 'text' of undefined
  at InsertRegister.execute (/Users/tommunro/github/atom-vim-mode-plus/lib/insert-mode.coffee:16:45)
  at OperationStack.module.exports.OperationStack.process (/Users/tommunro/github/atom-vim-mode-plus/lib/operation-stack.coffee:79:10)
  at vimState.input.readInput.onConfirm (/Users/tommunro/github/atom-vim-mode-plus/lib/base.coffee:62:34)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at InputBase.confirm (/Users/tommunro/github/atom-vim-mode-plus/lib/input.coffee:79:16)
  at /Users/tommunro/github/atom-vim-mode-plus/lib/input.coffee:30:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1592:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1551:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:404:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:648:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:553:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:472:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:745:29
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2033:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1999:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:435:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -1:04.8.0 core:cancel (atom-text-editor.editor.vim-mode-input.mini.is-focused)
     -1:04.3.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-input.mini.is-focused)
     -1:04.3.0 core:cancel (atom-text-editor.editor.vim-mode-input.mini.is-focused)
     -1:04.2.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-input.mini.is-focused)
     -1:04.2.0 core:cancel (atom-text-editor.editor.vim-mode-input.mini.is-focused)
     -1:00.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:00.1.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:43.4.0 find-and-replace:show (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:23 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:22 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.2.0 vim-mode:set-register-name (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:12.9.0 vim-mode:yank (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.4.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:06.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:05.6.0 vim-mode:insert-register (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_STORE",
      "._*",
      "Thumbs.db",
      ".png",
      ".prefab",
      ".scene",
      ".meta"
    ],
    "packagesWithKeymapsDisabled": [
      "omnisharp-atom",
      "advanced-new-file",
      "recent-files-fuzzy-finder"
    ],
    "disabledPackages": [
      "vim-mode",
      "isearch"
    ]
  },
  "vim-mode-plus": {
    "enableHoverIndicator": true,
    "enableHoverIcon": true,
    "stayOnTransformString": true,
    "enableHoverSearchCounter": true,
    "enableIncrementalSearch": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v6.0.17
atom-yeoman, v0.3.14
clipboard-plus, v0.5.1
cursor-history, v0.4.18
custom-search, v0.0.1
fuzzy-finder, v0.89.0
json-schema, v0.1.13
language-csharp, v0.10.0
linter, v1.6.0
linter-coffeelint, v1.1.0
omnisharp-atom, v0.23.0
recent-files-fuzzy-finder, v0.2.0
remember-file-positions, v0.1.5
save-session, vundefined
symbols-tree-view, v0.10.0
theme-switcher, v1.1.0
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.1.0

# Dev
find-and-replace, v0.175.0
omnisharp-atom, v0.22.5
settings-view, v0.219.0
```

**Comment by t9md** [comment]
I'm not sure original Vim have numbered register.
At least official vim-mode don't support numbered register.

https://github.com/atom/vim-mode/blob/master/keymaps/vim-mode.cson#L239-L294

Unlike vim-mode, vim-mode-plus don't directly keymap for each of 2 stroke register setting command.
What I'm thinking now is simply ignoreing invalid register character.

Thanks for reporting.

**Comment by t9md** [comment]
Fixe this.
By the way, original Vim have numbered register, and more.
So I want to support these register in future, but this is a big topic, not treat in this issue.
I will close since throwing error issue was fixed.
