### ISSUE TITLE
Uncaught Error: class 'MoveDown' not found

### ISSUE THREAD

**Issue by op-and** [t9md/atom-vim-mode-plus#1006]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.24.4

### Stack Trace

Uncaught Error: class 'MoveDown' not found

```
At /Users/pgoel/.atom/packages/vim-mode-plus/lib/base.js:830

Error: class 'MoveDown' not found
    at Function.getClass (/packages/vim-mode-plus/lib/base.js:830:13)
    at getClass (/packages/vim-mode-plus/lib/base.js:883:24)
    at /packages/vim-mode-plus/lib/base.js:889:51)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -4:17 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:52.7.0 find-and-replace:find-next (input.hidden-input)
     -3:46.6.0 go-to-line:toggle (input.hidden-input)
     -3:44.3.0 core:cancel (input.hidden-input)
     -3:40.9.0 find-and-replace:find-next (input.hidden-input)
  2x -0:04.7.0 vim-mode-plus:move-down (input.hidden-input)
  3x -0:03.2.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-vim-colon-command-on-command-pallete 0.2.0 
roku-develop 0.1.4 
vim-mode-plus 1.24.4 
```

**Comment by mnoble01** [comment]
I got this same error. I just needed to wait for the package updates to be installed and then restart Atom when prompted.
