### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by yelled1** [t9md/atom-vim-mode-plus#1012]
[Enter steps to reproduce:]

1. ...Connected to Remote Kernel (redhat unix) in Hydrogen for Win7
2. ...Error msg appeared as soon as I attempted to insert mode by typing in 'i' character & error msg comes back every time I hit 'i'

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.25.0

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At C:\Users\sy29314\.atom\packages\atom-vim-mode-plus-1.25.0\lib\operation-stack.js:151

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-vim-mode-plus-1.25.0/lib/pair-finder.js:9:35)
    at /packages/atom-vim-mode-plus-1.25.0/lib/pair-finder.js:281:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-vim-mode-plus-1.25.0/lib/text-object.js:9:20)
    at /packages/atom-vim-mode-plus-1.25.0/lib/text-object.js:886:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.1/resources/app/src/native-compile-cache.js:66:33)
    at Function.getClass (/packages/atom-vim-mode-plus-1.25.0/lib/base.js:203:21)
    at Function.getInstance (/packages/atom-vim-mode-plus-1.25.0/lib/base.js:214:56)
    at ActivateInsertMode.getInstance (/packages/atom-vim-mode-plus-1.25.0/lib/base.js:86:29)
    at ActivateInsertMode.initialize (/packages/atom-vim-mode-plus-1.25.0/lib/operator.js:139:27)
    at Function.getInstance (/packages/atom-vim-mode-plus-1.25.0/lib/base.js:217:12)
    at OperationStack.run (/packages/atom-vim-mode-plus-1.25.0/lib/operation-stack.js:86:26)
    at /packages/atom-vim-mode-plus-1.25.0/lib/vim-state.js:67:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  2x -1:15.9.0 hydrogen:connect-to-remote-kernel (div.package-detail.panels-item)
  2x -0:53.2.0 vim-mode-plus:move-up (input.hidden-input)
     -0:52.3.0 hydrogen:run-and-move-down (input.hidden-input)
     -0:50.3.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:50.1.0 vim-mode-plus:mark (input.hidden-input)
     -0:50 vim-mode-plus:set-input-char-p (input.hidden-input)
     -0:49.9.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
```

### Non-Core Packages

```
atom-space-pen-views 2.2.0 
vim-mode-plus 1.25.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
editorconfig 2.2.2 
ex-mode 0.18.0 
git-plus 7.10.0 
Hydrogen 2.2.0 
ink 0.7.11 
intentions 1.1.5 
isotope-ui 2.8.5 
julia-client 0.6.6 
language-julia 0.14.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-recent 5.0.0 
remote-edit 1.9.0 
tool-bar 1.1.0 
vim-mode-plus 1.25.0 
```

**Comment by yelled1** [comment]
either solution:
https://github.com/atom/bracket-matcher/issues/169
or 
fact I may have installed it twice caused prb.
 /drives/c/users/sy29314/AppData/Local/atom/bin/apm.cmd uninstall vim-mode-plus
& still works (think two diff package directories had it)
anyway works now.
