### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by yangxuanx** [t9md/atom-vim-mode-plus#1050]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 17.10
**Thrown From**: [atom-vim-mode-plus-1.31.1](https://github.com/t9md/atom-vim-mode-plus) package 1.31.1

### Stack Trace

Failed to activate the atom-vim-mode-plus-1.31.1 package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at VimState.matchScopes (/packages/atom-vim-mode-plus-1.31.1/lib/vim-state.js:135:18)
    at /packages/atom-vim-mode-plus-1.31.1/lib/vim-state.js:119:53)
    at subscriptions.atom.workspace.observeTextEditors.editor (/packages/atom-vim-mode-plus-1.31.1/lib/main.js:44:50)
    at Workspace.observeTextEditors (/snap/atom/136/usr/share/atom/resources/app/src/workspace.js:637:59)
    at Object.activate (/packages/atom-vim-mode-plus-1.31.1/lib/main.js:42:22)
    at Package.activateNow (/snap/atom/136/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/snap/atom/136/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/snap/atom/136/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/snap/atom/136/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/snap/atom/136/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/snap/atom/136/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/snap/atom/136/usr/share/atom/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/snap/atom/136/usr/share/atom/resources/app/src/package-manager.js:440:30)
    at emitter.on (/snap/atom/136/usr/share/atom/resources/app/src/config.js:1023:22)
    at Function.module.exports.Emitter.simpleDispatch (/snap/atom/136/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/snap/atom/136/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/snap/atom/136/usr/share/atom/resources/app/src/config.js:1175:62)
    at Config.setRawValue (/snap/atom/136/usr/share/atom/resources/app/src/config.js:1008:23)
    at Config.set (/snap/atom/136/usr/share/atom/resources/app/src/config.js:711:18)
    at Config.removeAtKeyPath (/snap/atom/136/usr/share/atom/resources/app/src/config.js:901:16)
    at Package.enable (/snap/atom/136/usr/share/atom/resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (/snap/atom/136/usr/share/atom/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/snap/atom/136/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
  5x -1:36.8.0 vim-mode:move-down (input.hidden-input)
 22x -1:35.5.0 vim-mode:move-up (input.hidden-input)
 58x -1:33.4.0 vim-mode:move-down (input.hidden-input)
  8x -1:30.8.0 vim-mode:move-to-next-word (input.hidden-input)
 58x -1:29 vim-mode:move-down (input.hidden-input)
 81x -1:26.4.0 vim-mode:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-languageclient 0.9.4 
vim-mode-plus 1.31.1 
event-kit 2.4.0 
ide-java 0.8.2 
vim-mode 0.66.0 
```

**Comment by t9md** [comment]
Can you reproduce it always? And how?
Please check following issue template.

https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md
