### ISSUE TITLE
Failed to load the vim-mode-plus package

### ISSUE THREAD

**Issue by Spectrum2008** [t9md/atom-vim-mode-plus#1056]
[Enter steps to reproduce:]

1. ...simply i changed the cson keymap after the 311 line 
2. ...i  dont know where is comming from nothing seems strange.

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.32.0

### Stack Trace

Failed to load the vim-mode-plus package

```
At Duplicate key '#'

Error: Duplicate key '#'
    at Object.detectDuplicateKeys (<embedded>:39386:19)
    at addProperty (<embedded>:170667:42)
    at Array.reduce (native)
    at Obj (<embedded>:170659:34)
    at transformNode (<embedded>:170735:18)
    at Value (<embedded>:170616:18)
    at transformNode (<embedded>:170735:18)
    at addProperty (<embedded>:170666:21)
    at Array.reduce (native)
    at Obj (<embedded>:170659:34)
    at transformNode (<embedded>:170735:18)
    at Value (<embedded>:170616:18)
    at transformNode (<embedded>:170735:18)
    at Block (<embedded>:170613:18)
    at transformNode (<embedded>:170735:18)
    at Object.parse (<embedded>:170741:22)
    at parseObject (<embedded>:39135:29)
    at parseContentsSync (<embedded>:39161:22)
    at Object.readFileSync (<embedded>:39273:20)
    at keymaps.getKeymapPaths.map (<embedded>:72717:20)
    at Array.map (native)
    at Package.loadKeymaps (<embedded>:72715:50)
    at measure (<embedded>:72396:20)
    at Package.measure (<embedded>:72351:25)
    at Package.load (<embedded>:72392:16)
    at PackageManager.loadAvailablePackage (<embedded>:25658:16)
    at config.transact (<embedded>:25571:20)
    at Config.transact (<embedded>:22331:20)
    at PackageManager.loadPackages (<embedded>:25569:23)
    at loadStatePromise.loadState.then (<embedded>:1069:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
emmet 2.4.3 
file-icons 2.1.18 
seti-icons 1.5.4 
vim-mode-plus 1.32.0 
```

**Comment by t9md** [comment]
Read message.
Check if line 311 in your keymap.cson define duplicate `#` keymap.
I believe you have `#` keymap at the line above 311 already and this is not vmp issue.

**Comment by kirkpams** [comment]
This error gets thrown immediately when starting Atom from the command line. I tried disabling and re-enabling vim-mode-plus afterward and it didn't change anything. This also has the side effect of dropping all projects from the window, even after restarting Atom from the Applications menu.

Steps to reproduce:

1. Install Atom + Vim-mode-plus
2. Select Atom -> Install Shell Commands
3. Run atom command from the terminal

**Atom Version**: 1.7.3
**System**: Mac OS X 10.14.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v1.36.4


### Stack Trace

Failed to load the vim-mode-plus package

```
At Unexpected token {

SyntaxError: Unexpected token {
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
vim-mode-plus, v1.36.4

# Dev
No dev packages
```

**Comment by t9md** [comment]
The latest Atom version in stable channel is 1.51.0. Are you really using 1.7.3 or is it typo?

**Comment by kirkpams** [comment]
Sorry for the confusion. I do have 1.51.0 installed, but I also had an old 1.7.3 hanging around. I had accidentally linked my command line tools to that version. I've fixed my configuration and everything is fine now. My apologies.
