### ISSUE TITLE
Uncaught Error: missing terminating ] for character class

### ISSUE THREAD

**Issue by EliHunter173** [t9md/atom-vim-mode-plus#1109]
1. Open up a file.
2. Search by entering `/[]`.
3. Error thrown.

**Atom**: 1.32.2 x64
**Electron**: 2.0.12
**OS**: linux 4.19.1-arch1-1-ARCH
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.36.0

### Stack Trace

Uncaught Error: missing terminating ] for character class

```
At /usr/lib/atom/node_modules/superstring/index.js:252

Error: missing terminating ] for character class
    at TextBuffer.findAllInRangeSync (/usr/lib/atom/node_modules/superstring/index.js:252:44)
    at TextBuffer.findAllInRangeSync (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1682:58)
    at TextBuffer.scanInRange (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1536:30)
    at TextBuffer.scan (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1479:17)
    at TextEditor.scan (/usr/lib/atom/src/text-editor.js:3530:24)
    at SearchModel.search (/packages/vim-mode-plus/lib/search-model.js:126:17)
    at Search.search (/packages/vim-mode-plus/lib/motion-search.js:101:26)
    at Search.handleChangeSearch (/packages/vim-mode-plus/lib/motion-search.js:190:12)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at SearchInput.editor.onDidChange (/packages/vim-mode-plus/lib/search-input.js:42:20)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at disposables.add.displayLayer.onDidChange.changes (/usr/lib/atom/src/text-editor.js:610:20)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at DisplayLayer.emitDeferredChangeEvents (/usr/lib/atom/node_modules/text-buffer/lib/display-layer.js:814:20)
    at TextBuffer.emitDidChangeTextEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:2360:22)
    at TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1333:10)
    at TextEditor.transact (/usr/lib/atom/src/text-editor.js:2002:24)
    at mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:1429:19)
    at TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:3419:20)
    at TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:3390:36)
    at TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1428:17)
    at TextEditor.insertText (/usr/lib/atom/src/text-editor.js:1381:25)
    at TextEditorComponent.didTextInput (/usr/lib/atom/src/text-editor-component.js:1652:24)
```

### Commands

```
     -0:49.1.0 vim-mode-plus:move-down (input.hidden-input)
 10x -0:48.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:47.1.0 vim-mode-plus:move-down (input.hidden-input)
     -0:46.9.0 vim-mode-plus:move-right (input.hidden-input)
     -0:46.2.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:45.4.0 vim-mode-plus:insert-after (input.hidden-input)
     -0:44.8.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:44.2.0 intentions:highlight (input.hidden-input)
     -0:44 code-format:format-code (input.hidden-input)
  2x -0:43.6.0 vim-mode-plus:move-up (input.hidden-input)
 17x -0:43 vim-mode-plus:move-down (input.hidden-input)
     -0:40.8.0 vim-mode-plus:search (input.hidden-input)
  3x -0:21 core:backspace (input.hidden-input)
     -0:19.7.0 vim-mode-plus:move-down-to-edge (input.hidden-input)
     -0:18.8.0 vim-mode-plus:search (input.hidden-input)
 14x -0:16.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
file-icons 2.1.26 
ide-css 0.3.0 
ide-java 0.8.3 
ide-json 0.2.1 
ide-python 1.0.0 
intentions 1.1.5 
letter-spacing 0.3.2 
linter-javac 1.9.4 
linter-ui-default 1.7.1 
vim-mode-plus 1.36.0 
```

**Comment by segeeslice** [comment]
Issue still occuring a year later..
