### ISSUE TITLE
Uncaught Error: Cannot find module './mark-manager'

### ISSUE THREAD

**Issue by Starxyz** [t9md/atom-vim-mode-plus#1124]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.36.0

### Stack Trace

Uncaught Error: Cannot find module './mark-manager'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module './mark-manager'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at VimState.load (/packages/vim-mode-plus/lib/vim-state.js:39:57)
    at /packages/vim-mode-plus/lib/vim-state.js:42:59)
    at /packages/vim-mode-plus/lib/operator-insert.js:170:24
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1208969)
    at VimState.activate (/packages/vim-mode-plus/lib/vim-state.js:461:20)
    at /packages/vim-mode-plus/lib/main.js:146:54)
    at HTMLElement.didDispatch (/packages/vim-mode-plus/lib/main.js:187:50)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -7:05.3.0 git-diff:move-to-next-diff (input.hidden-input)
     -5:51.1.0 editor:newline (input.hidden-input)
     -5:48.4.0 core:move-down (input.hidden-input)
     -5:48.1.0 autocomplete-plus:confirm (input.hidden-input)
 10x -5:47.6.0 core:backspace (input.hidden-input)
     -5:16.8.0 tree-view:toggle-focus (input.hidden-input)
     -5:09.1.0 tree-view:toggle-side (input.hidden-input)
     -0:17.4.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:12.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
vim-mode-plus 1.36.0 
```

**Comment by Starxyz** [comment]
i don't konw what happen...  it pops up a button and take me here.
