### ISSUE TITLE
Uncaught Error: Selection is not empty in normal-mode

### ISSUE THREAD

**Issue by NixusCN** [t9md/atom-vim-mode-plus#114]
[Enter steps to reproduce below:]
**Atom Version**: 1.3.2
**System**: Ubuntu 15.10
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.13.0

### Stack Trace

Uncaught Error: Selection is not empty in normal-mode

```
At /home/nixus/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:39

Error: Selection is not empty in normal-mode
    at OperationStack.finish (/home/nixus/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:80:19)
    at OperationStack.process (/home/nixus/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:69:8)
    at OperationStack.run (/home/nixus/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:35:8)
    at run (/home/nixus/.atom/packages/vim-mode-plus/lib/base.coffee:14:29)
    at atom-text-editor.<anonymous> (/home/nixus/.atom/packages/vim-mode-plus/lib/base.coffee:167:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 13x -1:00.5.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:57.5.0 vim-mode-plus:move-to-previous-word (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  5x -0:56.2.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:54.3.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:53 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode)
  3x -0:53 blur (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode)
     -0:51.2.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:48.2.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:40.5.0 project-find:show (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:40.4.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:33.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:33.3.0 blur (atom-text-editor.editor.mini.is-focused)
 28x -0:25.1.0 core:move-down (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:04.0 core:confirm (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  3x -0:03.7.0 blur (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:01.3.0 vim-mode-plus:scroll-cursor-to-middle-leave (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "jslint"
    ]
  },
  "vim-mode-plus": {
    "useClipboardAsDefaultRegister": true,
    "wrapLeftRightMotion": true,
    "useSmartcaseForSearch": true,
    "incrementalSearch": true,
    "stayOnTransformString": true,
    "stayOnYank": true,
    "flashOnUndoRedo": true,
    "showHoverOnOperate": true,
    "showHoverSearchCounter": true,
    "debug": true,
    "setCursorToStartOfChangeOnUndoRedo": true,
    "showHoverOnOperateIcon": "emoji"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.2
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
atom-ternjs, v0.12.2
autocomplete-php, v0.3.7
javascript-snippets, v1.0.0
jshint, v1.8.3
jslint, v1.5.1
language-javascript-better, v1.7.1
linter, v1.11.3
linter-csslint, v1.1.0
linter-golinter, v1.1.0
linter-jscs, v3.2.1
linter-jsonlint, v1.1.4
linter-jsxhint, v0.1.2
linter-oclitnt, v0.0.3
linter-php, v1.1.6
linter-phpcs, v1.3.0
linter-phpmd, v1.3.2
nuclide, v0.0.0
php-cs-fixer, v2.5.1
pigments, v0.19.5
react, v0.12.10
symbols-tree-view, v0.11.0
sync-settings, v0.6.0
tabularize, v0.2.5
vim-mode-plus, v0.13.0

# Dev
No dev packages
```

**Comment by brandon-fryslie** [comment]
I ran into this today.  I was editing a yaml file, I had used 'dd' to cut the top four lines from the file that I had selected using the keyboard.  I was in visual mode when I cut the lines.  Here are the lines:

    Operator: changed
    Value: null
  - AttributeID: ae8ecc9f-b9a0-42a4-a6e3-c83d7f8a7070
  - Defect

I can now reproduce it semi-consistently.  If I use the keyboard to go into visual mode, then use the mouse to make a selection, then cut it with 'd', I consistently see the error.  Interestingly enough I can only reproduce it with the lines I pasted above (not arbitrary text).  And when I just tried it, the error came when I hit 'u' to undo the change.  

And here's the error report:

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.13.0


### Stack Trace

Uncaught Error: Selection is not empty in normal-mode

```
At /Users/bfryslie/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:39

Error: Selection is not empty in normal-mode
    at OperationStack.finish (/Users/bfryslie/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:80:19)
    at OperationStack.process (/Users/bfryslie/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:69:8)
    at OperationStack.run (/Users/bfryslie/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:35:8)
    at run (/Users/bfryslie/.atom/packages/vim-mode-plus/lib/base.coffee:14:29)
    at atom-text-editor.<anonymous> (/Users/bfryslie/.atom/packages/vim-mode-plus/lib/base.coffee:167:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at __bind (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.__bind (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -0:47.5.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:45.5.0 core:close (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
  6x -0:45.5.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:17.9.0 pane:show-previous-item (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:17.9.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:16.2.0 core:backspace (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:14.3.0 core:paste (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  2x -0:11 core:select-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  5x -0:09.1.0 core:select-right (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  2x -0:07.8.0 core:move-left (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:06.2.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:05.8.0 core:select-right (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:02.8.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
     -0:01.3.0 vim-mode-plus:lower-case (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode)
  4x -0:01.3.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode)
     -0:00.8.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "projectHome": "/Users/bfryslie/projects"
  },
  "vim-mode-plus": {
    "incrementalSearch": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-ternjs, v0.12.2
atom-yamljson, v0.2.3
autocomplete-modules, v1.3.1
git-diff-details, v0.21.0
indent-guide-improved, v1.4.5
jumpy, v2.0.10
language-rust, v0.4.5
last-cursor-position, v0.9.0
linter, v1.11.3
linter-jsonlint, v1.1.4
linter-rust, v0.3.0
open-recent, v4.0.1
pretty-json, v0.4.1
sort-lines, v0.12.0
vim-mode-plus, v0.13.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
@brandon-fryslie  Thanks for very valuable information!
I want to fix this, but I still can't reproduce on my Mac and vim-mode-plus v0.13.0 and same configuration and buffer content you pasted above?

You can consistently reproduce issue like 3/10 success rate something like that?
I use following text

```yaml
    Operator: changed
    Value: null
  - AttributeID: ae8ecc9f-b9a0-42a4-a6e3-c83d7f8a7070
  - Defect
```
and `v` on first row of column 0, then shift-click mouse to expand selection, then `d`.

I tried with `V` and different starting point, but I couldn't.
Please help me to reproduce.

**Comment by t9md** [comment]
close in favor of #123 .
