### ISSUE TITLE
Failed to activate the vim-mode-plus package

### ISSUE THREAD

**Issue by PointedEars** [t9md/atom-vim-mode-plus#136]
[Enter steps to reproduce below:]

1. Started Atom with one Java editor tab restored.  (Happens with several JavaScript editors as well.)

**Atom Version**: 1.4.0
**System**: Debian GNU/Linux
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.16.0

### Stack Trace

Failed to activate the vim-mode-plus package

```
At VimState is not a function

TypeError: VimState is not a function
    at /home/pelinux/.atom/packages/vim-mode-plus/lib/main.coffee:33:22
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:288:9)
    at Object.module.exports.activate (/home/pelinux/.atom/packages/vim-mode-plus/lib/main.coffee:31:31)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at new Promise (/usr/local/atom/packages/recent-projects/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:197:7)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-tabs",
      "autocomplete-awk",
      "linter-pylint",
      "git-grep",
      "linter-xmllint",
      "fixmyjs",
      "move-status-items",
      "php-class-tree",
      "branch-status",
      "multi-file-open",
      "column-select",
      "es6-javascript",
      "es-navigation",
      "linter-mixed-indent"
    ],
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "themes": [
      "seti-ui",
      "lcars-syntax"
    ]
  },
  "vim-mode-plus": {
    "flashOnUndoRedo": true,
    "incrementalSearch": true,
    "stayOnTransformString": true,
    "stayOnYank": true,
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.12.2
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-bibtex, v0.6.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.4.4
autocomplete-xml, v0.8.1
autoupdate-packages, v1.3.1
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.0.14
compare-files, v0.6.2
css-snippets, v0.9.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.3.17
emmet-snippets-compatibility, v1.0.1
file-icons, v1.6.13
filesize, v0.4.2
fold-comments, v0.5.0
git-diff-details, v0.21.0
git-go, v1.0.1
git-hide, v0.1.2
git-log, v0.4.1
highlight-selected, v0.11.1
hyperclick, v0.0.35
hyperclick-php, v0.2.1
javascript-snippets, v1.2.0
js-hyperclick, v1.4.1
js-refactor, v0.6.0
keyboard-localization, v1.4.13
latex, v0.28.2
latexer, v0.2.7
lcars-syntax, v0.0.1
line-count-status, v0.0.3
line-jumper, v0.14.1
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-chktex, v1.2.4
linter-csslint, v1.2.0
linter-htmlhint, v1.0.0
linter-jshint, v1.2.2
linter-less, v2.3.3
linter-shellcheck, v1.1.0
local-history, v3.2.3
method-separator, v0.1.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
nav-panel, v0.0.11
navigate, v0.1.13
navigate-indent, v0.1.0
nuclide-url-hyperclick, v0.0.35
open-recent, v4.0.1
php-debug, v0.1.4
php-extract-method, v0.2.1
php-getters-setters, v0.5.5
pigments, v0.19.6
punchclock, v0.6.5
python-isort, v0.0.7
python-tools, v0.6.7
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.1
revert-buffer, v0.5.0
seti-ui, v0.8.1
svn, v0.0.9
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
up2date, v0.1.2
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.16.0
xkcd-comics, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by t9md** [comment]
Report again if its still effective.
Originally reported version is too old.
