### ISSUE TITLE
Uncaught TypeError: event.target.getModel is not a function

### ISSUE THREAD

**Issue by gregmacfarlane** [t9md/atom-vim-mode-plus#163]
From edit mode, hit `esc` to return to ex-mode.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.21.1

### Stack Trace

Uncaught TypeError: event.target.getModel is not a function

```
At /Users/Greg/.atom/packages/vim-mode-plus/lib/main.coffee:108

TypeError: event.target.getModel is not a function
    at atom-text-editor.<anonymous> (/Users/Greg/.atom/packages/vim-mode-plus/lib/main.coffee:108:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  8x -2:22.5.0 blur (input.hidden-input)
     -1:05.1.0 vim-mode-plus:move-down (input.hidden-input)
  6x -0:39.8.0 vim-mode-plus:move-up (input.hidden-input)
  3x -0:30.4.0 blur (input.hidden-input)
     -0:08.7.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:04.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:03.5.0 core:backspace (input.hidden-input)
  3x -0:03.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-lintr",
      "linter-chktex",
      "markdown-preview",
      "vim-mode",
      "Hydrogen"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4
auto-update-packages, v1.0.0
browser-plus, v0.0.54
compare-files, v0.6.2
file-watcher, v0.4.0
git-diff-details, v0.21.0
git-log, v0.4.1
language-gisdk, v0.2.1
language-knitr, v0.2.0
language-latex, v0.6.1
language-r, v0.4.0
language-x86, v0.1.0
latex, v0.29.0
latexer, v0.2.9
line-ending-converter, v1.3.2
linter, v1.11.3
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-git-diff, v4.1.8
pdf-view, v0.39.0
tablr, v1.0.2
tree-view-git-status, v0.2.2
vim-mode-plus, v0.21.1
vim-mode-visual-block, v0.2.15

# Dev
No dev packages
```

**Comment by t9md** [comment]
Not sure why this happen.
Can you reproduce it all the time you hit Esc twice(I couldn't)?

**Comment by slavaGanzin** [comment]
I get this time to time, and not shire about conditions

**Comment by t9md** [comment]
Sorry this inconcenience.
I will recert code to more conservative one.

**Comment by t9md** [comment]
released as v0.21.2.
Want to know if issue disappear.

**Comment by t9md** [comment]
No response for a while,, I think I can fix.

**Comment by gregmacfarlane** [comment]
Seems not to have come back; if I see again I will reopen.

**Comment by t9md** [comment]
OK, thanks.
