### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by barberousse** [t9md/atom-vim-mode-plus#178]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.22.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Users/bbarberousse/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:102

TypeError: Cannot read property 'style' of undefined
    at CursorStyleManager.refresh (/Users/bbarberousse/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:102:45)
    at VimState.module.exports.VimState.refreshCursors (/Users/bbarberousse/.atom/packages/vim-mode-plus/lib/vim-state.coffee:205:25)
    at /Users/bbarberousse/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:29:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ModeManager.activate (/Users/bbarberousse/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:80:14)
    at VimState._results.push._this.(anonymous function) [as activate] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/delegato/lib/delegator.js:67:61)
    at /Users/bbarberousse/.atom/packages/vim-mode-plus/lib/vim-state.coffee:169:10
    at /Users/bbarberousse/.atom/packages/vim-mode-plus/lib/vim-state.coffee:195:9
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:270:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
     -4:09.1.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -4:09.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -4:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 59x -4:08.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "followSymlinks": false,
    "themes": [
      "one-dark-ui",
      "sepia-syntax"
    ]
  },
  "vim-mode-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
file-type-icons, v0.7.4
git-plus, v5.13.0
language-babel, v2.15.4
language-elm, v1.3.2
linter, v1.11.3
linter-eslint, v7.0.0
sepia-syntax, v1.0.5
vim-mode-plus, v0.22.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Sorry I did quick fix without enough investigation.
Just revert changed code to more conservative one.
Sorry for that.
Will release in a minutes.
