### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Byron-TW** [t9md/atom-vim-mode-plus#186]
This one is very similar to #185, as it just happens while navigating.
I have a hunch that it might be related to my workflow of using insert mode more extensively than one would do it in VIM, by navigating with standard atom hotkeys.
Maybe there is some unwanted interaction.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.23.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:45

TypeError: Cannot read property 'indexOf' of undefined
    at RepeatSearch.SearchBase.getPattern (/Users/sthiel/.atom/packages/vim-mode-plus/lib/motion.coffee:832:12)
    at RepeatSearch.SearchBase.scan (/Users/sthiel/.atom/packages/vim-mode-plus/lib/motion.coffee:816:19)
    at RepeatSearch.SearchBase.moveCursor (/Users/sthiel/.atom/packages/vim-mode-plus/lib/motion.coffee:765:43)
    at /Users/sthiel/.atom/packages/vim-mode-plus/lib/motion.coffee:72:8
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1680:9)
    at RepeatSearch.Motion.execute (/Users/sthiel/.atom/packages/vim-mode-plus/lib/motion.coffee:71:13)
    at OperationStack.execute (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:74:28)
    at OperationStack.process (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:71:8)
    at OperationStack.run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:37:8)
    at run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:200:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:29.3.0 find-and-replace:show (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:29.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:27.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:27.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 vim-mode-plus:search (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:27.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:27 editor:consolidate-selections (atom-text-editor.editor.vim-mode-plus-search.mini.is-focused)
     -0:27 core:cancel (atom-text-editor.editor.vim-mode-plus-search.mini.is-focused)
  2x -0:27 blur (atom-text-editor.editor.vim-mode-plus-search.mini.is-focused)
  2x -0:26.8.0 vim-mode-plus:repeat-search (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:25.9.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:25.2.0 vim-mode-plus:search (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:25.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  6x -0:23.2.0 core:backspace (atom-text-editor.editor.vim-mode-plus-search.mini.is-focused)
  6x -0:13.4.0 blur (atom-text-editor.editor.vim-mode-plus-search.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint"
    ],
    "excludeVcsIgnoredPaths": true,
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "git-blame",
      "vim-mode-plus",
      "es6-javascript",
      "emmet",
      "node-debugger"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "vim-mode-plus": {
    "flashOnUndoRedo": true,
    "highlightSearch": true,
    "incrementalSearch": true,
    "setCursorToStartOfChangeOnUndoRedo": true,
    "stayOnTransformString": true,
    "stayOnYank": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
atom-beautify, v0.28.26
atom-material-ui, v1.2.0
atom-ternjs, v0.13.2
atom-typescript, v8.3.0
autocomplete-ctags, v0.4.0
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
build, v0.55.0
build-cargo, v0.12.0
build-make, v0.7.0
cargo-test-runner, v0.0.5
coffee-compile, v0.21.1
css-snippets, v0.9.0
cursor-history, v0.5.9
emmet, v2.4.2
expand-region, v0.2.4
git-plus, v5.13.0
javascript-snippets, v1.2.1
language-apache, v1.4.0
language-elm, v1.3.3
language-escript, v0.1.0
language-jade, v0.6.3
language-mako, v0.6.0
language-rust, v0.4.6
linter, v1.11.3
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-elm-make, v0.4.0
linter-eslint, v7.0.0
linter-flake8, v1.13.0
linter-golinter, v1.2.0
linter-htmlhint, v1.0.3
linter-javac, v1.8.0
linter-js-standard, v3.2.1
linter-js-yaml, v1.2.5
linter-jscs, v3.4.8
linter-jsonlint, v1.1.6
linter-jsxhint, v0.1.2
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pylint, v1.2.0
linter-python-pep8, v0.2.0
linter-ruby, v1.2.2
linter-rust, v0.4.1
linter-sass-lint, v1.1.1
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
linter-tslint, v0.8.3
linter-xmllint, v1.3.4
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
node_modules, vundefined
pretty-json, v0.4.1
preview, v0.16.6
project-manager, v2.7.6
racer, v0.18.0
react, v0.14.1
react-es6-snippets, v0.3.0
react-snippets, v0.3.0
rust-api-docs-helper, v0.5.1
snippets-jade, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0
tablr, v1.0.2
vim-mode-plus, v0.23.0
you-complete-me, v0.7.1

# Dev
No dev packages
```

**Comment by t9md** [comment]
Degradation introduced in #181, will handle in #199

**Comment by t9md** [comment]
Removed my comment to avoid confusion that was my misunderstanding.

**Comment by t9md** [comment]
I will close to re-evaluate this issue still happen since the code base was greatly changed from initial report.
