### ISSUE TITLE
Failed to load the vim-mode-plus package

### ISSUE THREAD

**Issue by edomos** [t9md/atom-vim-mode-plus#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.1.6

### Stack Trace

Failed to load the vim-mode-plus package

```
At Cannot find module 'emoji-images'

Error: Cannot find module 'emoji-images'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\hover.coffee:4:9)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\hover.coffee:3:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\vim-state.coffee:4:11)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\vim-state.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\main.coffee:5:12)
  at Object.<anonymous> (C:\Users\Петя\.atom\packages\vim-mode-plus\lib\main.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:485:30)
  at C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Петя\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -1:50.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:48.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:48.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:47.2.0 core:undo (atom-text-editor.editor.is-focused)
     -1:46.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:45.9.0 core:close (atom-text-editor.editor.is-focused)
     -1:45.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:44.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:42.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:42.7.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:59.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:59.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:56.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:56.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:47.1.0 core:cancel (table.package-keymap-table.table.native-key-bindings.text)
     -0:34.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
laravel, v0.7.0
vim-mode-plus, v0.1.6

# Dev
No dev packages
```

**Comment by t9md** [comment]
I don't have windows, it seems fail to install depending package `emoji-images`.
Could you try uninstall vim-mode-plus from GUI then retry from cli with apm install vim-mode-plus and paste console output?

I want information from any other windows user who succeeded to use vim-mode-plus.

**Comment by t9md** [comment]
close since no update.

**Comment by haasDev** [comment]
got a similar error but a result of a duplicate key.

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.66.1


### Stack Trace

Failed to load the vim-mode-plus package

```
At Duplicate key 'g _'

Error: Duplicate key 'g _'
  at Object.detectDuplicateKeys (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:268:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:387:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:384:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:110:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:466:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:410:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:772:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "ex-mode"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "oceanic-next-italic"
    ]
  },
  "vim-mode-plus": {
    "highlightSearch": true,
    "incrementalSearch": true,
    "showHoverSearchCounter": true,
    "smoothScrollOnFullScrollMotion": true,
    "smoothScrollOnHalfScrollMotion": true,
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-ternjs, v0.16.1 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
auto-update-packages, v1.0.1 (inactive)
autocomplete-modules, v1.6.7 (inactive)
caniuse, v0.9.0 (inactive)
color-picker, v2.2.3 (inactive)
docblockr, v0.8.7 (inactive)
editorconfig, v2.0.5 (inactive)
elm-format, v2.1.0 (inactive)
file-icons, v1.7.25 (inactive)
flex-tool-bar, v0.11.0 (inactive)
git-diff-details, v1.4.0 (inactive)
haskell-grammar, v0.4.0 (inactive)
highlight-selected, v0.11.2 (inactive)
language-elm, v1.5.0 (inactive)
language-ini, v1.16.0 (inactive)
language-ocaml, v1.1.2 (inactive)
language-svg, v0.9.0 (inactive)
language-thrift, v1.0.2 (inactive)
linter, v1.11.18 (inactive)
linter-elm-make, v0.17.8 (inactive)
linter-eslint, v8.0.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.6 (inactive)
minimap-git-diff, v4.3.1 (inactive)
multi-cursor, v2.1.3 (inactive)
oceanic-next, v0.4.0 (inactive)
oceanic-next-italic, v1.0.1 (inactive)
open-recent, v5.0.0 (inactive)
pain-split, v1.4.0 (inactive)
pigments, v0.37.0 (inactive)
platformio-ide-terminal, v2.2.2 (inactive)
react, v0.16.1 (inactive)
relative-numbers, v0.5.1 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.6 (inactive)
svg-preview, v0.10.0 (inactive)
sync-settings, v0.7.2 (inactive)
todo-show, v1.8.0 (inactive)
tool-bar, v1.0.1 (inactive)
vim-mode-plus, v0.66.1 (inactive)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```
