### ISSUE TITLE
Incremental search window doesn't dismiss on blur, shows on top of non-TextEditor items

### ISSUE THREAD

**Issue by tmunro** [t9md/atom-vim-mode-plus#2]
1. Open settings
2. Open a text editor item
3. Start searching with `/`
4. Select settings tab and click inside it to lose focus on incremental search window
5. Incremental search window remains
6. Select text editor again
7. Begin searching with `/`
8. A second incremental search window appears, and the first is now broken

This issue also occurs if you invoke the command palette and then attempt to return to a search.

**Atom Version**: 1.0.11-278e988
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/vim-mode-plus) package, v0.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/tommunro/github/atom-vim-mode-plus/lib/vim-state.coffee:153

TypeError: undefined is not a function
  at OperationStack.module.exports.OperationStack.process (/Users/tommunro/github/atom-vim-mode-plus/lib/operation-stack.coffee:51:20)
  at /Users/tommunro/github/atom-vim-mode-plus/lib/operation-stack.coffee:32:8
  at OperationStack.module.exports.OperationStack.withLock (/Users/tommunro/github/atom-vim-mode-plus/lib/operation-stack.coffee:37:7)
  at OperationStack.module.exports.OperationStack.push (/Users/tommunro/github/atom-vim-mode-plus/lib/operation-stack.coffee:31:6)
  at atom-text-editor.commands.(anonymous function) (/Users/tommunro/github/atom-vim-mode-plus/lib/vim-state.coffee:150:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:22.5.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:21.5.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:21.5.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:20.5.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:20.5.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:19.6.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:19.6.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:19.2.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:19.2.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:15.2.0 vim-mode:search (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.4.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:14.4.0 core:cancel (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:09.2.0 vim-mode:search (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.4.0 pane:show-previous-item (atom-text-editor.editor.vim-mode-search.mini.is-focused)
     -0:05.2.0 pane:show-next-item (div.settings-view.pane-item)
     -0:04.3.0 vim-mode:search (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_STORE",
      "._*",
      "Thumbs.db",
      ".png",
      ".prefab",
      ".scene",
      ".meta"
    ],
    "packagesWithKeymapsDisabled": [
      "omnisharp-atom",
      "advanced-new-file",
      "recent-files-fuzzy-finder"
    ],
    "disabledPackages": [
      "vim-mode",
      "isearch"
    ]
  },
  "vim-mode-plus": {
    "enableHoverIndicator": true,
    "enableHoverIcon": true,
    "stayOnTransformString": true,
    "enableHoverSearchCounter": true,
    "enableIncrementalSearch": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v6.0.17
atom-yeoman, v0.3.14
clipboard-plus, v0.5.1
cursor-history, v0.4.18
custom-search, v0.0.1
fuzzy-finder, v0.89.0
json-schema, v0.1.13
language-csharp, v0.10.0
linter, v1.6.0
linter-coffeelint, v1.1.0
omnisharp-atom, v0.23.0
recent-files-fuzzy-finder, v0.2.0
remember-file-positions, v0.1.5
save-session, vundefined
symbols-tree-view, v0.10.0
theme-switcher, v1.1.0
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.1.0

# Dev
find-and-replace, v0.175.0
omnisharp-atom, v0.22.5
settings-view, v0.219.0
```

**Comment by t9md** [comment]
I intentionally skip blur event handler while Im in active development phase for selector investigation purpose. But yes I will fix this after my refactoring for incremental search part finished.
Thanks for very explanatory report.
