### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of null

### ISSUE THREAD

**Issue by erik-escobedo** [t9md/atom-vim-mode-plus#233]
[Enter steps to reproduce below:]

1. I tried to delete a block by typing `d}`.
2. It didn't work, so I tried to delete it by typing `d17G`.

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.33.0

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of null

```
At /Users/erik/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:53

TypeError: Cannot read property 'row' of null
    at Function.module.exports.Point.fromObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:30:23)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:113:24)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:175:32)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:82:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at MoveToLastLine.MoveToFirstLine.moveCursor (/Users/erik/.atom/packages/vim-mode-plus/lib/motion.coffee:496:12)
    at /Users/erik/.atom/packages/vim-mode-plus/lib/motion.coffee:107:8
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:977:7)
    at MoveToLastLine.Motion.selectInclusively (/Users/erik/.atom/packages/vim-mode-plus/lib/motion.coffee:106:15)
    at MoveToLastLine.Motion.select (/Users/erik/.atom/packages/vim-mode-plus/lib/motion.coffee:80:10)
    at Delete.Operator.selectTarget (/Users/erik/.atom/packages/vim-mode-plus/lib/operator.coffee:115:13)
    at Delete.Operator.mutateSelections (/Users/erik/.atom/packages/vim-mode-plus/lib/operator.coffee:134:9)
    at Delete.Operator.execute (/Users/erik/.atom/packages/vim-mode-plus/lib/operator.coffee:147:6)
    at OperationStack.execute (/Users/erik/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:85:27)
    at OperationStack.process (/Users/erik/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:66:10)
    at OperationStack.run (/Users/erik/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:46:8)
    at Function.Base.run (/Users/erik/.atom/packages/vim-mode-plus/lib/base.coffee:243:31)
    at atom-text-editor.<anonymous> (/Users/erik/.atom/packages/vim-mode-plus/lib/base.coffee:238:66)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:09.8.0 pane:show-item-1 (input.hidden-input)
  3x -0:09.8.0 blur (input.hidden-input)
  4x -0:09.1.0 vim-mode-plus:move-up (input.hidden-input)
     -0:07.3.0 vim-mode-plus:inner-current-line (input.hidden-input)
     -0:06.3.0 vim-mode-plus:inner-indentation (input.hidden-input)
     -0:05.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:05.2.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:04.5.0 core:backspace (input.hidden-input)
     -0:04.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:03.6.0 vim-mode-plus:undo (input.hidden-input)
     -0:03.4.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:02.7.0 vim-mode-plus:move-down (input.hidden-input)
     -0:01.8.0 vim-mode-plus:delete (input.hidden-input)
     -0:01.3.0 vim-mode-plus:set-count-1 (input.hidden-input)
     -0:01.0 vim-mode-plus:set-count-6 (input.hidden-input)
     -0:00.7.0 vim-mode-plus:move-to-last-line (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "motepair",
      "vim-mode"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-html-entities, v0.1.0
keyboard-localization, v1.4.18
language-emblem, v0.2.0
language-haml, v0.24.0
linter, v1.11.4
linter-jshint, v2.1.0
vim-mode-plus, v0.33.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Bug when destination row is completely empty for MoveToFristLine(`gg`) and MoveToLastLine(`G`)
Will fixed v0.33.1 and will release it in hour.
