### ISSUE TITLE
Failed to activate the vim-mode-plus package

### ISSUE THREAD

**Issue by yetone** [t9md/atom-vim-mode-plus#256]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.36.0

### Stack Trace

Failed to activate the vim-mode-plus package

```
At Cannot find module 'undefined/lib/selection-wrapper'

Error: Cannot find module 'undefined/lib/selection-wrapper'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at requireFrom (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/utils.coffee:5:3)
    at Object.<anonymous> (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/utils.coffee:7:9)
    at Object.<anonymous> (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/utils.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/move-selected-text.coffee:8:5)
    at Object.<anonymous> (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/move-selected-text.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.consumeVim (/Users/yetone/.atom/packages/vim-mode-plus-move-selected-text/lib/main.coffee:44:5)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:352:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:06.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:06.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:02.6.0 settings-view:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 16x -3:02.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  9x -2:33.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:30.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:30.9.0 core:cancel (atom-text-editor.editor.is-focused)
 12x -2:27.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:25.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:25.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:23.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:22.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:22.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:22.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:19.1.0 settings-view:open (atom-text-editor.editor.is-focused)
 39x -2:19 blur (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode-next",
      "linter-pyflakes",
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-erlang, v0.6.19
autocomplete-ctags, v0.4.1
autocomplete-go, v1.0.6
autocomplete-js-import, v1.0.1
autocomplete-json, v1.9.1
autocomplete-python, v1.7.2
clipboard-plus, v0.5.1
go-config, v1.1.4
go-get, v1.0.3
language-babel, v2.18.0
linter, v1.11.4
linter-eslint, v7.2.1
linter-flake8, v1.13.0
minimap, v4.22.1
minimap-git-diff, v4.3.0
react, v0.15.0
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus-jasmine-increase-focus, v0.2.0
vim-mode-plus-move-selected-text, v0.5.0
vim-mode-plus-move-to-symbols, v0.1.4
vim-mode-plus-replace-with-execution, v0.1.1
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1
vue-autocomplete, v0.1.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
What situation you saw this issue?
Install vim-mode-plus and deactivate vim-mode then restart atom.

**Comment by yetone** [comment]
@t9md fixed, thx 👍 👍 👍

**Comment by BetterWang** [comment]
@yetone how did you fix it? thanks.

**Comment by yetone** [comment]
@BetterWang remove vim-mode then restart atom

**Comment by afdallah-war** [comment]
Thanks @t9md
