### ISSUE TITLE
Uncaught TypeError: bs.getHead is not a function

### ISSUE THREAD

**Issue by treuss** [t9md/atom-vim-mode-plus#257]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 15.10
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.36.0

### Stack Trace

Uncaught TypeError: bs.getHead is not a function

```
At /home/treuss/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:67

TypeError: bs.getHead is not a function
    at /home/treuss/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:67:73
    at Array.map (native)
    at CursorStyleManager.refresh (/home/treuss/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:67:58)
    at VimState.module.exports.VimState.updateCursorsVisibility (/home/treuss/.atom/packages/vim-mode-plus/lib/vim-state.coffee:24:3)
    at ModeManager.activate (/home/treuss/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:56:6)
    at VimState._results.push._this.(anonymous function) [as activate] (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/delegato/lib/delegator.js:67:61)
    at VimState.commands.activate-blockwise-visual-mode (/home/treuss/.atom/packages/vim-mode-plus/lib/main.coffee:100:7)
    at atom-text-editor.<anonymous> (/home/treuss/.atom/packages/vim-mode-plus/lib/main.coffee:123:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:04.4.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:04.0 vim-mode-plus:move-to-end-of-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:03.9.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:03.9.0 blur (atom-text-editor.editor.vim-mode-plus-input.mini.is-focused)
     -0:03.8.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.7.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.3.0 editor:consolidate-selections (atom-text-editor.editor.vim-mode-plus-input.mini.is-focused)
     -0:03.3.0 core:cancel (atom-text-editor.editor.vim-mode-plus-input.mini.is-focused)
  2x -0:03.3.0 blur (atom-text-editor.editor.vim-mode-plus-input.mini.is-focused)
     -0:03.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:02.8.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:02.3.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  4x -0:01.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.9.0 vim-mode-plus:activate-blockwise-visual-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -0:00.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.blockwise)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "vim-mode-plus": {
    "highlightSearch": true,
    "ignoreCaseForSearch": true,
    "incrementalSearch": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
clipboard-plus, v0.5.1
merge-conflicts, v1.4.2
monokai, v0.18.0
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.36.0
vim-mode-plus-move-to-symbols, v0.1.4
vim-surround, v0.8.1
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by t9md** [comment]
This issue is very strange since bs.getHead is not even exist in the code.
I renamed `bs.getHead()` to `bs.getHeadSelection()` before, this renaming timing is v0.33.0 release.

Can you explain more context of this error, any thought from information I put above?

**Comment by treuss** [comment]
If I remember correctly, this happened right after installing vim-mode-plus and testing visual block mode via CTRL-v in command mode.
Hope this helps :)

**Comment by t9md** [comment]
Ok. This is one time issue i believe when you upgraded recent vmp version.
So i have nothing to do for this issue, close.
