### ISSUE TITLE
Uncaught TypeError: operation.execute is not a function

### ISSUE THREAD

**Issue by downsea** [t9md/atom-vim-mode-plus#317]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.49.0

### Stack Trace

Uncaught TypeError: operation.execute is not a function

```
At /Users/nice/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:53

TypeError: operation.execute is not a function
    at OperationStack.execute (/Users/nice/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:84:27)
    at OperationStack.process (/Users/nice/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:66:10)
    at OperationStack.run (/Users/nice/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:46:8)
    at Function.Base.run (/Users/nice/.atom/packages/vim-mode-plus/lib/base.coffee:265:31)
    at atom-text-editor.<anonymous> (/Users/nice/.atom/packages/vim-mode-plus/lib/base.coffee:259:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/nice/apps/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/nice/apps/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/nice/apps/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/nice/apps/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/nice/apps/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/nice/apps/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:22.5.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:21.9.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:21.6.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.operator-pending-mode.delete-pending)
     -0:21.3.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:21 vim-mode-plus:insert-after (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  2x -0:17.8.0 core:backspace (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
     -0:14.6.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
     -0:13.6.0 vim-mode-plus:put-after (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:12.8.0 core:save (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  4x -0:09.9.0 blur (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:09.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.insert-mode.is-focused)
  2x -0:08.4.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:07.2.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:04.1.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode.autocomplete-active)
     -0:04.1.0 snippets:expand (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode.autocomplete-active)
     -0:00.6.0 vim-mode-plus:inner-function (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "nuclide",
      "activate-power-mode",
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3
atom-ctags, v4.5.2
autocomplete-R, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.8.4
color-picker, v2.2.2
docblockr, v0.7.3
elastic-tabstops, v1.1.1
file-types, v0.5.2
language-r, v0.4.1
language-scala, v1.1.6
markdown-preview-plus, v2.4.0
minimap, v4.24.7
quick-highlight, v0.5.0
regex-railroad-diagram, v0.16.0
relative-numbers, v0.5.1
symbols-tree-view, v0.13.2
terminal-plus, v0.14.5
vim-mode, v0.65.1
vim-mode-plus, v0.49.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by t9md** [comment]
thanks for reporting. will handle in #318
