### ISSUE TITLE
Uncaught TypeError: this.resetNormalMode is not a function

### ISSUE THREAD

**Issue by mahmoudhossam** [t9md/atom-vim-mode-plus#347]
[Enter steps to reproduce below:]

1. ... Open new pane with Ctrl + n
2. ... Press Ctrl + W then ESC to close.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.53.0

### Stack Trace

Uncaught TypeError: this.resetNormalMode is not a function

```
At /home/mahmoud/.atom/packages/vim-mode-plus/lib/main.coffee:149

TypeError: this.resetNormalMode is not a function
    at commands.reset-normal-mode (/home/mahmoud/.atom/packages/vim-mode-plus/lib/main.coffee:149:32)
    at atom-text-editor.newCommands.(anonymous function) (/home/mahmoud/.atom/packages/vim-mode-plus/lib/main.coffee:181:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.simulateBubblingOnDetachedTarget (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:605:23)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:582:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:561:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:432:21)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 11x -3:24.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:23.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:19.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.2.0 application:open-your-keymap (atom-text-editor.editor.vim-mode-plus.normal-mode)
 47x -0:18.2.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:12.4.0 vim-mode-plus:insert-below-with-newline (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.7.0 editor:newline (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:06.5.0 core:paste (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:05.5.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  2x -0:05.3.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:04.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:02.7.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.2.0 core:close (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.2.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2 (active)
git-plus, v5.16.2 (inactive)
terminal-plus, v0.14.5 (active)
vim-mode-plus, v0.53.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for reporting.
This is the same issue  reported in #163.
I fixed #163 by adding condition check.

But in commit https://github.com/t9md/atom-vim-mode-plus/commit/c1474b09e1d2bbe5f6f33704a3394e0ee798417b, I removed this condition check since I'm not still sure why this is necessary and I optimistically hope that other change of vmp or Atom core might solve cause of this strange issue.

But was not.

Sorry I'll add condition check to fix.
