### ISSUE TITLE
Cannot edit jsx file (with syntax by "react" package)

### ISSUE THREAD

**Issue by averrin** [t9md/atom-vim-mode-plus#358]
# Check list

- Version info: **1.11.0-beta4**
- You disabled vim-mode? **Yes**
- Restarting Atom itself solve your problem? **No**
- Keybinding issue? **No**

Try press O or o in js (**only if syntax "JavaScript (JSX)"** by "react" package). Its cause:
```
Uncaught TypeError: this.getRegexForProperty is not a function
/home/user/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:54
Hide Stack Trace
TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/home/user/.atom/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:366:26)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:3550:32)
    at Selection.module.exports.Selection.insertText (/usr/share/atom-beta/resources/app.asar/src/selection.js:494:21)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:1063:29
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:1102:29
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1519:26)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:1096:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2497:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:2459:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1094:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1060:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom-beta/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1075:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (/usr/share/atom-beta/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:1414:24
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1519:26)
    at TextEditor.module.exports.TextEditor.insertNewlineBelow (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:1411:19)
    at InsertBelowWithNewline.insertNewline (/home/user/.atom/packages/vim-mode-plus/lib/operator.coffee:1240:13)
    at InsertBelowWithNewline.InsertAboveWithNewline.execute (/home/user/.atom/packages/vim-mode-plus/lib/operator.coffee:1228:6)
    at OperationStack.execute (/home/user/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:88:27)
    at OperationStack.process (/home/user/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:67:10)
    at OperationStack.run (/home/user/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:47:8)
    at atom-text-editor.<anonymous> (/home/user/.atom/packages/vim-mode-plus/lib/base.coffee:266:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

UPD: `A` and `i` is working, but i cant type anything. Everything works if i change syntax to basic js

**Comment by t9md** [comment]
I think first path to open issue is to atom-react package.
The `getRegexForProperty` seem to be function atom-react provides.

**Comment by t9md** [comment]
btw, I couldn't reproduce it.
- installed [atom-react](https://atom.io/packages/react)
- open js file, set grammar to jsx manually by `grammar selector show` command from command-palette.
- then `o` or `O` to enter insert-mode.

Also tried coffee jsx version, but couldn't reproduce it.

**Comment by averrin** [comment]
My way:
1. Enable react plugin ([this](https://atom.io/packages/react))
2. It asks to disable language-babel
3. Disable it and reload atom
4. Open file (e.g. [this](https://github.com/averrin/shodan-ui/blob/master/app/containers/ShodanPage.js))
5. Atom say its "JavaScript (JSX)" grammar
6. Try to edit
7. Error still here

So, language-babel doing same work and this bug not critical for me, you can close it without fix;)

**Comment by t9md** [comment]
OK, but as I explained in above message.
The function actually throwing error is not this package, that is atom-react package.
So my judge for this error is fix to being protective on atom-react side.
Even if vmp is related, its not essential vmp issue.
