### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#37]
[Enter steps to reproduce below:]

1. On the Atom beta
2. Try searching for anything.

**Atom Version**: 1.3.0-beta5
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/me/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:22

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at MarkerLayer.module.exports.MarkerLayer.findMarkers (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:133:21)
    at DisplayBuffer.module.exports.DisplayBuffer.findFoldMarkers (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer.js:1143:36)
    at saveEditorState (/Users/me/.atom/packages/vim-mode-plus/lib/utils.coffee:37:40)
    at Search.initialize (/Users/me/.atom/packages/vim-mode-plus/lib/motion.coffee:705:29)
    at Search.Base (/Users/me/.atom/packages/vim-mode-plus/lib/base.coffee:31:6)
    at Search.Motion [as constructor] (/Users/me/.atom/packages/vim-mode-plus/lib/motion.coffee:17:3)
    at SearchBase [as constructor] (/Users/me/.atom/packages/vim-mode-plus/lib/motion.coffee:589:3)
    at new Search (/Users/me/.atom/packages/vim-mode-plus/lib/motion.coffee:700:3)
    at OperationStack.run (/Users/me/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:20:17)
    at run (/Users/me/.atom/packages/vim-mode-plus/lib/base.coffee:12:27)
    at atom-text-editor.<anonymous> (/Users/me/.atom/packages/vim-mode-plus/lib/base.coffee:115:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:46.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:46.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:46.3.0 timecop:view (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode)
 36x -1:46.2.0 blur (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode)
     -0:43.3.0 settings-view:open (div.pane-item.native-key-bindings.about)
 16x -0:43.3.0 blur (div.pane-item.native-key-bindings.about)
     -0:03.5.0 pane:show-previous-item (div.panels-item)
     -0:03.5.0 blur (div.panels-item)
     -0:03.3.0 pane:show-previous-item (div.pane-item.native-key-bindings.about)
     -0:03.3.0 blur (div.pane-item.native-key-bindings.about)
     -0:02.9.0 pane:show-previous-item (div.timecop.pane-item.native-key-bindings)
     -0:02.9.0 blur (div.timecop.pane-item.native-key-bindings)
  3x -0:01.3.0 vim-mode-plus:move-up (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode.is-focused)
     -0:01.0 vim-mode-plus:search (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode.is-focused)
     -0:00.7.0 vim-mode-plus:mark (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode.is-focused)
     -0:00.7.0 blur (atom-text-editor.editor.hidden-gutters.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "minimap-selection",
      "nuclide-toolbar",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-debugger-lldb",
      "nuclide-test-runner",
      "nuclide-remote-projects",
      "wrap-guide",
      "atom-html-preview"
    ]
  },
  "vim-mode-plus": {
    "incrementalSearch": true,
    "flashOnSearch": false,
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true,
    "flashOnOperate": false,
    "flashScreenOnSearchHasNoMatch": false
  }
}
```

### Installed Packages

```coffee
# User
language-ocaml, v1.1.2
language-swift, v0.4.0
markdown-preview-opener, v0.1.1
toggle-gutter, v0.2.2
vim-mode-plus, v0.4.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for quick catch.

I myself not using Atom-dev channel, will try and check later.
Every atom version-up breaks some of package I'm maintaining...

**Comment by yanite** [comment]
me too error
atom 1.3.1 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Unknown Windows Version
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.3.0


### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:35

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at MarkerLayer.module.exports.MarkerLayer.findMarkers (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:133:21)
    at DisplayBuffer.module.exports.DisplayBuffer.findFoldMarkers (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\src\display-buffer.js:1143:36)
    at saveEditorState (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/utils.coffee:37:40)
    at Search.initialize (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/motion.coffee:706:29)
    at Search.Base (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/base.coffee:31:6)
    at Search.Motion [as constructor] (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/motion.coffee:17:3)
    at SearchBase [as constructor] (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/motion.coffee:590:3)
    at new Search (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/motion.coffee:701:3)
    at OperationStack.run (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:20:17)
    at run (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/base.coffee:12:27)
    at atom-text-editor.<anonymous> (file:///C:/Users/yanite1/.atom/packages/vim-mode-plus/lib/base.coffee:115:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\yanite1\AppData\Local\atom\app-1.3.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -4:19.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:12.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:03.9.0 blur (button.btn.icon.enablement.icon-playback-pause)
  7x -3:02.2.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -3:01.5.0 vim-mode-plus:search (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -2:58.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
 17x -2:55.1.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -1:58.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 19x -1:55 blur (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 vim-mode-plus:search (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:03.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "run-in-terminal",
      "markdown-preview",
      "angularjs",
      "ult-terminal",
      "atom-terminal",
      "atom-terminal-panel",
      "language-clojure",
      "language-gfm",
      "language-go",
      "language-make",
      "language-toml",
      "welcome",
      "quick-jump",
      "language-x86-64-assembly",
      "quick-highlight",
      "metrics",
      "QuickMenu",
      "browser-plus",
      "autocomplete-python",
      "language-autohotkey",
      "increment-selection",
      "selection-highlight",
      "language-git",
      "java-importer",
      "line-ending-selector",
      "devdocs",
      "quickdoc",
      "atomerinal",
      "clip-history",
      "dash",
      "toggle-packages",
      "atom-javascript-console-snippets",
      "aligner",
      "clipboard-plus",
      "script",
      "scroll-sync",
      "api-docs"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-terminal",
      "run-in-terminal",
      "vim-mode",
      "view-mode",
      "highlight-line",
      "quick-query",
      "native-ui",
      "fuzzy-finder",
      "web-browser",
      "activate-power-mode",
      "autocomplete-modules",
      "highlight-selected",
      "editor-background",
      "auto-fold",
      "iojs-debugger",
      "node-debugger",
      "project-folder"
    ],
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "G:\\work_project"
  },
  "vim-mode-plus": {
    "wrapLeftRightMotion": true,
    "useSmartcaseForSearch": true,
    "incrementalSearch": true,
    "stayOnTransformString": true,
    "flashOnOperate": false,
    "flashOnSearch": false,
    "flashScreenOnSearchHasNoMatch": false,
    "showHoverOnOperate": true,
    "showHoverSearchCounter": true,
    "debug": true,
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
atom-commander, v0.5.0
atom-json-editor, v0.4.0
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
debugger, v0.0.1
editor-background, v1.2.14
emmet, v2.3.14
emmet-snippets-compatibility, v1.0.1
file-icons, v1.6.11
file-type-icons, v0.7.4
fold-functions, v0.4.3
fonts, v1.0.0
goto-last-edit, v0.2.2
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.11.1
htmlhint, v1.1.3
jQuery, v1.2.0
language-cpp14, v0.4.2
language-sql-mysql, v0.3.1
last-cursor-position, v0.9.0
linter-htmlhint, v0.2.1
local-history, v3.2.3
navigate, v0.1.13
navigation-history, v0.1.8
nerd-treeview, v0.3.1
node-debugger, v1.1.9
open-recent, v4.0.1
project-manager, v2.6.5
remember-file-positions, v0.2.0
restore-windows, v0.4.1
save-session, v0.15.7
shadow, v0.1.0
symbols-tree-view, v0.10.1
terminal-panel, v1.14.1
tree-view-filter, v0.3.9
tree-view-open-files, v0.3.0
vim-mode-plus, v0.3.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
update vim-mode-plus to latest v0.8.0
