### ISSUE TITLE
Uncaught TypeError: op.execute is not a function when executing A Function, Inner Function

### ISSUE THREAD

**Issue by tmunro** [t9md/atom-vim-mode-plus#4]
1. Open a file (I used .cs and .coffee to test)
2. Navigate to the body of a function
3. Use command palette to invoke vim-mode-plus:a-function or Inner Function
4. Observe type error

It's also possible I'm just not sure how to invoke this. I tried to invoke it in operator pending mode as well, but got no result.

**Atom Version**: 1.0.19-5f4f6d2
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.1.1

### Stack Trace

Uncaught TypeError: op.execute is not a function

```
At /Users/tommunro/.atom/packages/vim-mode-plus/lib/vim-state.coffee:159

TypeError: op.execute is not a function
  at OperationStack.module.exports.OperationStack.process (/Users/tommunro/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:79:10)
  at /Users/tommunro/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:32:8
  at OperationStack.module.exports.OperationStack.withLock (/Users/tommunro/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:37:7)
  at OperationStack.module.exports.OperationStack.push (/Users/tommunro/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:31:6)
  at atom-text-editor.commands.(anonymous function) (/Users/tommunro/.atom/packages/vim-mode-plus/lib/vim-state.coffee:156:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:16.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:13.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:13.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:12.6.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:11.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:09.6.0 blur (atom-text-editor.editor.mini.is-focused)
  8x -0:07.5.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.0 vim-mode-plus:a-function (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:01.9.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_STORE",
      "._*",
      "Thumbs.db",
      ".png",
      ".prefab",
      ".scene",
      ".meta"
    ],
    "packagesWithKeymapsDisabled": [
      "omnisharp-atom",
      "advanced-new-file",
      "recent-files-fuzzy-finder"
    ],
    "disabledPackages": [
      "vim-mode",
      "isearch"
    ]
  },
  "vim-mode-plus": {
    "enableIncrementalSearch": true,
    "showHoverOnOperate": true,
    "showHoverSearchCounter": true,
    "useSmartcaseForSearch": true,
    "incrementalSearch": true,
    "stayOnTransformString": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-yeoman, v0.3.14
clipboard-plus, v0.5.1
cursor-history, v0.4.18
custom-search, v0.0.1
fuzzy-finder, v0.90.0
json-schema, v0.1.13
language-csharp, v0.10.0
linter, v1.6.0
linter-coffeelint, v1.1.0
omnisharp-atom, v0.24.14
recent-files-fuzzy-finder, v0.2.0
remember-file-positions, v0.1.5
save-session, vundefined
symbols-tree-view, v0.10.0
theme-switcher, v1.1.0
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.1.1
zentabs, v0.8.6

# Dev
omnisharp-atom, v0.22.5
settings-view, v0.219.0
```

**Comment by t9md** [comment]
This issue is not only for text-obj Function.
All text-obj have this issue since execute method is not implemented on text-obj.

Simply using Select operator as operator when tex-obj is directly pushed to operation stack will solve this issue.
Ill try later.
NOTE:
As a rule of operationStack when operation is directly executed it call execute method of pushed operation, if operation is used as target of another operation targeted operation is called its select method.
This is same as official vim-mode.
