### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of null

### ISSUE THREAD

**Issue by huang47** [t9md/atom-vim-mode-plus#416]
This is the same issue like #233 where atom said it's already reported (6 months) ago. It's happened when I do shift+v > d to delete a row and errors show up

<img width="1235" alt="screen shot 2016-10-01 at 09 02 51" src="https://cloud.githubusercontent.com/assets/157390/19015278/0d9fc0f8-87b6-11e6-948a-86862cfeaa4e.png">

# Check list

- Atom version info(`atom --version`)
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
- vim-mode-plus version.
0.58.2
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
yes
- Tried to latest stable atom version with latest vim-mode-plus.
yes
- Restarting Atom itself solve your problem?
no

**Comment by t9md** [comment]
Could you paste stacktrace you see in your screenshot?
You can re-produce 100%. Want to give sample text you.
I thought I could fix that in v0.58.2. but seems is not fixed. So I need above information to understand issue correctly.

**Comment by huang47** [comment]
@t9md  thanks for the lighting fast response

yes I can reproduce this 100% (I suppose) at least during all of my attempts I can repro it at will.
Also, this issue exists in both 0.58.0 / 0.58.2 and downgraded it to 0.57.0 which works for me

stacktrace
> TypeError: Cannot read property 'row' of null
  at Function.module.exports.Point.fromObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:30:23)
  at Point.module.exports.Point.traverse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:115:21)
  at CurrentSelection.moveCursor (/Users/huang47/.atom/packages/vim-mode-plus/lib/motion.coffee:158:40)
  at /Users/huang47/.atom/packages/vim-mode-plus/lib/motion.coffee:110:8
  at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:972:7)
  at CurrentSelection.Motion.selectInclusively (/Users/huang47/.atom/packages/vim-mode-plus/lib/motion.coffee:109:15)
  at CurrentSelection.Motion.select (/Users/huang47/.atom/packages/vim-mode-plus/lib/motion.coffee:79:10)
  at CurrentSelection.select (/Users/huang47/.atom/packages/vim-mode-plus/lib/motion.coffee:168:7)
  at DeleteLine.Operator.selectTarget (/Users/huang47/.atom/packages/vim-mode-plus/lib/operator.coffee:242:15)
  at DeleteLine.Operator.execute (/Users/huang47/.atom/packages/vim-mode-plus/lib/operator.coffee:191:9)
  at DeleteLine.Delete.execute (/Users/huang47/.atom/packages/vim-mode-plus/lib/operator.coffee:394:5)
  at DeleteLine.execute (/Users/huang47/.atom/packages/vim-mode-plus/lib/operator.coffee:437:5)
  at OperationStack.execute (/Users/huang47/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:141:27)
  at OperationStack.process (/Users/huang47/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:130:8)
  at OperationStack.run (/Users/huang47/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:95:10)
  at atom-text-editor.<anonymous> (/Users/huang47/.atom/packages/vim-mode-plus/lib/base.coffee:326:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

**Comment by t9md** [comment]
Thanks, could you also give a minimum text and keystroke (c-v then p?).
I want reproduce first in my environment,  but I couldn't easily (I tried but not yet reproducable).

**Comment by huang47** [comment]
`v` then `d` works, the problem occurred when doing `V` then `d` (`shift+v` then `d`)

let me know if I provide the sufficient information, didn't quite get what's the "minimum text" part

**Comment by t9md** [comment]
The sample text you can reproduce 100%.
I tried `V d` when you first opened this issue but no luck.

**Comment by huang47** [comment]
hm..I can try it later today to investigate further, good to know that it's not a wide-spread issue

**Comment by t9md** [comment]
Thanks, I'm taking this issue seriously and can provide fix from your stack trace now.
But before going forward, I want to understand situation.
Since I couldn't reproduce it by `V d` with different scenario.

**Comment by huang47** [comment]
could you send me a gist and I can patch it locally and see if it's fixed?

**Comment by t9md** [comment]
OK will try, but my patch would not ideal fix, just adding null guard.

**Comment by t9md** [comment]
https://gist.github.com/t9md/c0738157d3ecc498ae89d1b4784d09e8

**Comment by huang47** [comment]
yup it stops `Vd` throwing exceptions

It seems like it's because of the typing speed(I use some software which map the key speed to 10 ~ 20 ms) and if I type `Vd` fast enough it throws this exception. 

If I type `V` (wait for 200~300ms), and `d` and it's working

**Comment by t9md** [comment]
You use Karabiner?

**Comment by t9md** [comment]
I could reproduce without Karabiner! By typing `V` and `d` almost same time.
Will fix soon, thanks for information.

**Comment by t9md** [comment]
I understand situation correctly.
What we are typing when issue happens is not `V d`, we are typing `V D`.
So the issue is "throwing exception in VD keystroke".

**Comment by t9md** [comment]
handle in #417, Since I want to put memo about my thought, this is good example "Why immediate null guard is bad".

Btw, when you are using Karabiner, you might typing "V D" with thinking you are typing "V d", this is not just "V", all the "Shift" combination keystorkes or might include other Shift like modified keys.

The bad things is this might make your issue report really complicate like "you can reproduce easily" but "developer cannot reproduce it with exactly same keystrokes"
This is not your cause, but good to know the Karabiner's characteristics.

Thanks.

**Comment by t9md** [comment]
released v0.58.3. this issue teach me a lot 👍  Thanks!
