### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCount' of undefined

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#434]
I had entered some text, then hit `g;` or `g,`.  Both were crashing.

This doesn't seem easy to reproduce though...  I restarted Atom and did the same thing, but `g;` and `g,` are just being ignored.

Looking at the keymap it appears `g;` and `g,` aren't implemented yet...  so...  no idea!

**Atom Version**: 1.11.1
**vim-mode-plus version**: 0.60.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.60.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getCount' of undefined

```
At /Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:132

TypeError: Cannot read property 'getCount' of undefined
    at VimState._results.push._this.(anonymous function) [as getCount] (/Users/bronson/.atom/packages/vim-mode-plus/node_modules/delegato/lib/delegator.js:67:48)
    at Till.Base.getCount (/Users/bronson/.atom/packages/vim-mode-plus/lib/base.coffee:117:6)
    at Till.Find.getCount (/Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:761:5)
    at Till.Find.getPoint (/Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:744:5)
    at Till.getPoint (/Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:781:14)
    at Till.Find.moveCursor (/Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:764:14)
    at /Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:67:8
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2050:9)
    at Till.Motion.execute (/Users/bronson/.atom/packages/vim-mode-plus/lib/motion.coffee:66:13)
    at OperationStack.execute (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:156:27)
    at OperationStack.process (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:145:8)
    at OperationStack.run (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:101:10)
    at OperationStack.runCurrentFind (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:127:8)
    at VimState.commands.repeat-find (/Users/bronson/.atom/packages/vim-mode-plus/lib/main.coffee:131:41)
    at atom-text-editor.newCommands.(anonymous function) (/Users/bronson/.atom/packages/vim-mode-plus/lib/main.coffee:162:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:561:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:432:21)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:32.7.0 vim-mode-plus:insert-at-last-insert (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:30.8.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:29.4.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:29 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:07.5.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:06.9.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  7x -0:06.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.8.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.1.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:04.9.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  9x -0:04.8.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:03.8.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:03.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode.autocomplete-active)
     -0:02.8.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 12x -0:02.4.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.1.0 vim-mode-plus:repeat-find (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "exception-reporting",
      "welcome",
      "background-tips",
      "linter-jscs",
      "linter-reek",
      "metrics"
    ],
    "packagesWithKeymapsDisabled": [
      "rspec",
      "ruby-test-switcher",
      "rails-transporter",
      "todo-show"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-reef-syntax"
    ]
  },
  "vim-mode-plus": {
    "flashOnUndoRedo": true,
    "flashOnUndoRedoDuration": 300,
    "highlightSearch": true,
    "incrementalSearch": true,
    "setCursorToStartOfChangeOnUndoRedo": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (active)
atom-ternjs, v0.15.0 (active)
autocomplete-elixir, v1.5.14 (active)
color-picker, v2.2.2 (active)
cursor-history, v0.6.1 (active)
file-icons, v1.7.22 (active)
git-control, v0.8.2 (inactive)
git-plus, v5.18.0 (active)
git-time-machine, v1.5.3 (inactive)
highlight-selected, v0.11.2 (active)
language-apache, v1.6.0 (active)
language-elixir, v0.16.0 (active)
language-haml, v0.24.0 (active)
language-viml, v1.1.2 (active)
linter, v1.11.18 (active)
linter-coffeelint, v1.1.2 (active)
linter-csslint, v1.3.3 (active)
linter-elixir-credo, v1.1.0 (active)
linter-elixirc, v1.1.11 (active)
linter-erb, v1.0.2 (active)
linter-eslint, v8.0.0 (active)
linter-haml, v2.0.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-jscs, v4.1.0 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-reek, v2.1.5 (inactive)
linter-rubocop, v0.5.0 (active)
linter-ruby, v1.2.2 (active)
linter-tidy, v2.2.1 (active)
linter-write-good, v0.8.0 (active)
merge-conflicts, v1.4.4 (active)
oceanic-reef-syntax, v0.6.0 (active)
open-this, v0.2.0 (inactive)
paner, v0.4.0 (inactive)
phoenix-elixir-snippets, v0.4.0 (active)
project-find-navigation, v0.2.0 (active)
project-plus, v0.9.0 (active)
quick-editor, v0.4.3 (inactive)
rails-transporter, v1.6.5 (inactive)
react, v0.16.1 (active)
rspec, v0.3.2 (inactive)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-test-switcher, v1.2.3 (active)
script, v3.10.1 (inactive)
todo-show, v1.7.0 (inactive)
vim-mode-plus, v0.60.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
white-cursor, v0.6.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for reporting, and sorry for this regression.
This is also regression I unintentionally introduced when extracting repeat-find from motion.coffee

Will release hotfix soon.

**Comment by bronson** [comment]
No problem at all, I'm stoked to see vmp still getting tons of love.  (I still want to help out more too...  just need to find the time)

**Comment by t9md** [comment]
By the way, to reproduce issue.
`g` in `g ;` part is not related, what caused error is `,` and `;` its repeat-find and repeat-found-backward command.

When `;` or `,` is repeated **after original editor was destroyed**, it throw error.

**Comment by t9md** [comment]
released  v0.60.1

**Comment by sunjay** [comment]
@t9md This is still happening on v0.60.1.

1. Have a file open (happens even in a new/blank file window)
2. Press ';' 

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.60.1


### Stack Trace

Uncaught TypeError: Cannot read property 'getCount' of undefined

```
At /home/sunjay/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:132

TypeError: Cannot read property 'getCount' of undefined
    at VimState._results.push._this.(anonymous function) [as getCount] (/home/sunjay/.atom/packages/vim-mode-plus/node_modules/delegato/lib/delegator.js:67:48)
    at Till.Base.getCount (/home/sunjay/.atom/packages/vim-mode-plus/lib/base.coffee:133:84)
    at Till.Find.getCount (/home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:761:5)
    at Till.Find.getPoint (/home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:744:5)
    at Till.getPoint (/home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:781:14)
    at Till.Find.moveCursor (/home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:764:14)
    at /home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:67:8
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app.asar/src/text-editor.js:1934:9)
    at Till.Motion.execute (/home/sunjay/.atom/packages/vim-mode-plus/lib/motion.coffee:66:13)
    at OperationStack.execute (/home/sunjay/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:156:27)
    at OperationStack.process (/home/sunjay/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:145:8)
    at OperationStack.run (/home/sunjay/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:101:10)
    at OperationStack.runCurrentFind (/home/sunjay/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:127:8)
    at VimState.commands.repeat-find (/home/sunjay/.atom/packages/vim-mode-plus/lib/main.coffee:131:41)
    at atom-text-editor.newCommands.(anonymous function) (/home/sunjay/.atom/packages/vim-mode-plus/lib/main.coffee:162:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:11.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:11.2.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11 blur (atom-text-editor.editor.mini.is-focused)
     -0:10.7.0 vim-mode-plus-ex-mode:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:10.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:10.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:10.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.7.0 vim-mode-plus:insert-below-with-newline (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:02.9.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:00.7.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:00.2.0 vim-mode-plus:repeat-find (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "ex-mode",
      "language-gfm",
      "racer"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.4.1 (active)
ex-mode, v0.13.0 (inactive)
language-babel, v2.45.0 (active)
language-bnf, v1.1.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-markdown, v0.17.0 (active)
language-rust, v0.4.8 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-rust, v0.6.0 (active)
linter-scss-lint, v3.0.4 (active)
pigments, v0.37.0 (active)
project-manager, v3.2.5 (active)
racer, v0.20.0 (inactive)
sync-settings, v0.7.2 (active)
vim-mode, v0.65.1 (inactive)
vim-mode-plus, v0.60.1 (active)
vim-mode-plus-ex-mode, v0.5.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by t9md** [comment]
I can't reproduce it, and it's difficult to understand why still happens.
Your issue fixed when restarting atom?
If so, please give sample text and flow of operation(command, open files, keystrokes) if you can reproduce this issue always.
