### ISSUE TITLE
Uncaught TypeError: this.activate is not a function

### ISSUE THREAD

**Issue by henyihanwobushi** [t9md/atom-vim-mode-plus#50]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.7.1

### Stack Trace

Uncaught TypeError: this.activate is not a function

```
At /home/t/.atom/packages/vim-mode-plus/lib/main.coffee:53

TypeError: this.activate is not a function
    at vimStateCommands.reset-normal-mode (/home/t/.atom/packages/vim-mode-plus/lib/main.coffee:53:32)
    at atom-text-editor.<anonymous> (/home/t/.atom/packages/vim-mode-plus/lib/main.coffee:65:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.simulateBubblingOnDetachedTarget (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:558:23)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:535:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:507:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:383:23)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:57.9.0 blur (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode.characterwise)
     -3:56.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:56.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -3:35.8.0 settings-view:open (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  4x -3:35.6.0 blur (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -3:34.4.0 core:cancel (div.panels-item)
 29x -3:22.5.0 blur (div.panels-item)
     -0:08.8.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode.characterwise)
     -0:08.6.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:08.5.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  4x -0:07.9.0 vim-mode-plus:scroll-half-screen-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
 31x -0:04.9.0 vim-mode-plus:scroll-half-screen-up (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  4x -0:03.0 vim-mode-plus:scroll-half-screen-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:00.7.0 core:close (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  2x -0:00.7.0 blur (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:00.7.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {},
  "vim-mode-plus": {
    "useSmartcaseForSearch": true,
    "incrementalSearch": true
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.17.0
project-manager, v2.6.5
vim-mode, v0.63.0
vim-mode-plus, v0.7.1

# Dev
No dev packages
```

**Comment by t9md** [comment]
You seem to execute vim-mode-plus's command in settings-view's mini editor I believe.
Will be fixed in next release.

**Comment by bendavis78** [comment]
This becomes an issue for me when switching from a term2 pane

**Atom Version**: 1.3.2
**System**: linux 4.2.6-9ph
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.10.2


### Stack Trace

Uncaught TypeError: this.activate is not a function

```
At /home/ben/.atom/packages/vim-mode-plus/lib/main.coffee:52

TypeError: this.activate is not a function
    at vimStateCommands.reset-normal-mode (/home/ben/.atom/packages/vim-mode-plus/lib/main.coffee:52:32)
    at atom-text-editor.<anonymous> (/home/ben/.atom/packages/vim-mode-plus/lib/main.coffee:64:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.simulateBubblingOnDetachedTarget (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:561:23)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:538:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:510:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:386:23)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -0:13.2.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:12.4.0 core:save (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:12 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.4.0 core:close (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.2.0 vim-mode-plus:move-to-first-character-of-line-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:10.6.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:10.3.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:08.1.0 maximize-panes:maximize (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:04.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:04.1.0 core:page-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:03.7.0 core:page-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.6.0 maximize-panes:maximize (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:00.7.0 core:close (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:00.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:00.7.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-htmlhint",
      "minimap",
      "linter-polymer"
    ],
    "autoHideMenuBar": true
  },
  "vim-mode-plus": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.54
gutter-shadow, v0.6.0
hidpi, v0.10.0
linter, v1.11.3
linter-jshint, v1.2.1
maximize-panes, v0.2.0
project-manager, v2.6.5
term2, v0.9.21
toggle-gutter, v0.2.2
vim-mode-plus, v0.10.2

# Dev
No dev packages
```

**Comment by t9md** [comment]
Pls create new issue with precise procedure to reproduce.
