### ISSUE TITLE
Paste with cmd+v into find / text input causes error.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#510]
[Enter steps to reproduce below:]

1. Hit `/` to search.
2. Paste using `cmd+v`.

**Atom Version**: 1.13.0-beta2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.67.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:872

TypeError: Cannot read property 'start' of undefined
  at /Users/me/.atom/packages/vim-mode-plus/lib/search-model.coffee:44:44
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at SearchModel.module.exports.SearchModel.updateCurrentMatch (/Users/me/.atom/packages/vim-mode-plus/lib/search-model.coffee:120:14)
  at SearchModel.module.exports.SearchModel.search (/Users/me/.atom/packages/vim-mode-plus/lib/search-model.coffee:111:6)
  at SearchBase.search (/Users/me/.atom/packages/vim-mode-plus/lib/motion-search.coffee:95:19)
  at Search.handleChangeSearch (/Users/me/.atom/packages/vim-mode-plus/lib/motion-search.coffee:172:8)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at /Users/me/.atom/packages/vim-mode-plus/lib/search-input.coffee:32:16
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:541:32
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at DisplayLayer.module.exports.DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:367:27)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:730:29
  at Map.forEach (native)
  at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:729:41)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:713:19)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/selection.js:480:43)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2998:31
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1149:28
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1566:26)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1143:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2544:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2506:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1141:19)
  at TextEditor.module.exports.TextEditor.pasteText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2971:19)
  at TextEditor.core:paste (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:437:21)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:666:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1566:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:665:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

```

### Commands

```
  7x -0:10.7.0 vim-mode-plus:move-up (input.hidden-input)
     -0:09.9.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:08.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:07.9.0 vim-mode-plus:undo (input.hidden-input)
 13x -0:05.2.0 vim-mode-plus:move-up (input.hidden-input)
     -0:04.7.0 vim-mode-plus:search (input.hidden-input)
     -0:03.4.0 core:confirm (input.hidden-input)
  4x -0:03.4.0 blur (input.hidden-input)
  5x -0:03.2.0 vim-mode-plus:repeat-search (input.hidden-input)
     -0:01.9.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
     -0:01.8.0 vim-mode-plus:move-to-end-of-word (input.hidden-input)
     -0:01.6.0 vim-mode-plus:yank (input.hidden-input)
  6x -0:01.3.0 vim-mode-plus:move-up (input.hidden-input)
     -0:01.0 vim-mode-plus:search (input.hidden-input)
  3x -0:01.0 blur (input.hidden-input)
     -0:00.3.0 core:paste (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "minimap-selection",
      "nuclide-toolbar",
      "nuclide-react-native",
      "nuclide-navigation-stack",
      "nuclide-toolbar",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-debugger-lldb",
      "nuclide-test-runner",
      "nuclide-remote-projects",
      "wrap-guide",
      "whitespace",
      "metrics",
      "nuclide-hack-symbol-provider",
      "nuclide-hack",
      "nuclide-buck-files",
      "browser-plus",
      "git-diff",
      "background-tips",
      "lazy-motion",
      "nuclide-find-references",
      "tab-switcher",
      "tool-bar",
      "atom-html-preview",
      "markdown-preview",
      "bookmarks",
      "git-time-machine",
      "minimap",
      "atom-reason-loader",
      "atom-reason",
      "language-reason",
      "nerd-treeview"
    ],
    "followSymlinks": false,
    "telemetryConsent": "no",
    "useCustomTitleBar": true
  },
  "vim-mode-plus": {
    "clearMultipleCursorsOnEscapeInsertMode": true,
    "clearPersistentSelectionOnResetNormalMode": true,
    "flashOnOperate": false,
    "flashOnUndoRedo": false,
    "flashScreenOnSearchHasNoMatch": false,
    "highlightSearch": true,
    "incrementalSearch": true,
    "setCursorToStartOfChangeOnUndoRedo": true,
    "smoothScrollOnFullScrollMotion": true,
    "smoothScrollOnFullScrollMotionDuration": 100,
    "smoothScrollOnHalfScrollMotion": true,
    "smoothScrollOnHalfScrollMotionDuration": 100,
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true
  }
}
```

### Installed Packages

```coffee
# User
atom-reason, v0.0.5 (inactive)
atom-reason-loader, v0.5.0 (inactive)
focus-pane-or-panel, v0.2.0 (inactive)
language-reason, v0.0.10 (inactive)
linter, v1.11.19 (active)
markdown-preview-enhanced, v0.8.9 (active)
markdown-preview-opener, v0.1.1 (active)
nerd-treeview, v0.4.2 (inactive)
nuclide, v0.183.0 (active)
project-find-navigation, v0.3.0 (inactive)
vim-mode-plus, v0.67.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
vim-mode-plus-project-find-from-search, v0.1.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for reporting, this is degradation by my mistake in https://github.com/t9md/atom-vim-mode-plus/commit/09a0f9764c5f7b394fb3380a73b29330b79019fb.
