### ISSUE TITLE
tab/shift-tab in vL(visual-line) mode throw error

### ISSUE THREAD

**Issue by averrin** [t9md/atom-vim-mode-plus#619]
- Atom version info: 1.13-beta8

```
Uncaught TypeError: Cannot read property 'isGreaterThanOrEqual' of undefined
/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:121
Hide Stack Trace
TypeError: Cannot read property 'isGreaterThanOrEqual' of undefined
    at SelectionWrapper.getBufferPositionFor (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/selection-wrapper.coffee:61:14)
    at getOffset (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:29:38)
    at CursorStyleManager.refresh (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/cursor-style-manager.coffee:95:47)
    at VimState.module.exports.VimState.updateCursorsVisibility (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/vim-state.coffee:305:25)
    at OperationStack.finish (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:172:15)
    at OperationStack.execute (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:155:8)
    at OperationStack.process (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:138:8)
    at OperationStack.run (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:83:10)
    at atom-text-editor.<anonymous> (/home/alexeynabrodov/.atom/packages/vim-mode-plus/lib/base.coffee:341:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by t9md** [comment]
# Repro

1. on any file
2. `V` then `tab` or `shift-tab`

**Comment by t9md** [comment]
Thanks for reporting.
Will include next release(I can't release it immediately because of other issue)
