### ISSUE TITLE
Uncaught TypeError: editor.displayLayer.findFoldMarkers is not a function

### ISSUE THREAD

**Issue by admosity** [t9md/atom-vim-mode-plus#652]
Press `/` from any editor in normal mode.

**Atom**: 1.14.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.78.0

### Stack Trace

Uncaught TypeError: editor.displayLayer.findFoldMarkers is not a function

```
At /Users/cain/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:120

TypeError: editor.displayLayer.findFoldMarkers is not a function
    at saveEditorState (/packages/vim-mode-plus/lib/utils.coffee:52:39)
    at Search.initialize (/packages/vim-mode-plus/lib/motion-search.coffee:114:29)
    at /packages/vim-mode-plus/lib/motion.coffee:54:6)
    at /packages/vim-mode-plus/lib/motion-search.coffee:17:7)
    at /packages/vim-mode-plus/lib/motion-search.coffee:104:7)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.coffee:75:27)
    at /packages/vim-mode-plus/lib/base.coffee:329:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:52 linter:lint (atom-text-editor.editor.vim-mode-plus.visual-mode.linewise.is-focused)
     -0:51.2.0 core:close (input.hidden-input)
     -0:50.6.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:48.7.0 core:confirm (input.hidden-input)
     -0:48.5.0 linter:lint (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:35.7.0 tabs:open-in-new-window (div.title.icon.ts-icon.medium-blue)
  3x -0:31.1.0 pane:show-previous-item (input.hidden-input)
     -0:30.5.0 linter:lint (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:30.2.0 pane:show-previous-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30 linter:lint (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:28.6.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:28.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:25.8.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -0:23.7.0 linter:lint (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:22.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:08.9.0 vim-mode-plus:search (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.1.0 
atom-beautify 0.29.16 
atom-material-syntax 0.4.6 
atom-material-syntax-dark 0.2.5 
atom-material-syntax-light 0.4.5 
atom-material-ui 1.3.8 
atom-monokai 0.10.4 
atom-ternjs 0.16.1 
atom-typescript 10.1.13 
atom-wallaby 1.0.14 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
color-picker 2.2.3 
cursor-history 0.9.1 
docblockr 0.9.1 
editorconfig 2.1.0 
emmet 2.4.3 
file-icons 2.0.8 
fizzy 0.16.0 
git-blame 0.4.11 
git-time-machine 1.5.4 
highlight-selected 0.11.2 
language-babel 2.49.3 
language-cypher 0.3.0 
language-diff 0.6.0 
language-docker 1.1.7 
language-livescript-edge 1.0.2 
language-nginx 0.6.2 
language-pug 0.0.19 
language-swig 0.1.4 
lcov-info 0.12.0 
linter 1.11.21 
linter-eslint 8.0.0 
linter-htmlhint 1.3.1 
merge-conflicts 1.4.4 
minimap 4.26.5 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.4.0 
minimap-selection 4.4.0 
minimap-split-diff 0.3.2 
monokai 0.18.0 
monokai-light 0.3.7 
multirow-tabs 0.3.3 
my-theme-syntax 0.0.0 
open-on-bitbucket 0.4.0 
open-this 0.2.0 
pigments 0.38.0 
script 3.14.0 
seti-ui 1.4.0 
split-diff 1.1.1 
Sublime-Style-Column-Selection 1.7.2 
text-pastry 0.6.1 
transpose-selection 1.1.0 
uuidgen 1.2.1 
vim-mode-plus 0.78.0 
```

**Comment by alexcheninfo** [comment]
I have the same problem.

**Comment by t9md** [comment]
open new issue with necessary information.

**Comment by t9md** [comment]
OK, you have to provide me, necessary info. here is OK. check issue template when you see open new issue.

**Comment by alexcheninfo** [comment]
I updated to 0.88 and it's fine now. Sorry.
