### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by ysakmrkm** [t9md/atom-vim-mode-plus#672]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.82.0

### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At /Users/ysakmrkm/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:120

TypeError: Cannot read property 'text' of undefined
    at PutBefore.mutateSelection (/packages/vim-mode-plus/lib/operator.coffee:634:6)
    at /packages/vim-mode-plus/lib/operator.coffee:254:12
    at /packages/vim-mode-plus/lib/operator.coffee:240:9
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1548:26)
    at PutBefore.Operator.startMutation (/packages/vim-mode-plus/lib/operator.coffee:239:15)
    at PutBefore.Operator.execute (/packages/vim-mode-plus/lib/operator.coffee:247:6)
    at PutBefore.execute (/packages/vim-mode-plus/lib/operator.coffee:619:5)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.coffee:151:27)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.coffee:140:8)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.coffee:83:10)
    at /packages/vim-mode-plus/lib/base.coffee:328:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:09.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:09.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:08.7.0 vim-mode-plus:move-up (input.hidden-input)
     -0:08.2.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
  2x -0:08.0 vim-mode-plus:move-down (input.hidden-input)
     -0:07.5.0 vim-mode-plus:insert-at-start-of-target (input.hidden-input)
     -0:07.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:06.7.0 vim-mode-plus:put-before (input.hidden-input)
     -0:05.4.0 vim-mode-plus:insert-after-end-of-line (input.hidden-input)
     -0:04.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:04.3.0 vim-mode-plus:move-right (input.hidden-input)
     -0:03.7.0 vim-mode-plus:insert-after-end-of-line (input.hidden-input)
     -0:03.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:02.4.0 vim-mode-plus:replace-character (input.hidden-input)
     -0:02.1.0 vim-mode-plus:set-input-char-> (input.hidden-input)
     -0:01.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-wordpress-hooks 0.2.2 
block-selection-mode 0.3.0 
browser-plus 0.0.87 
compass 0.9.1 
editorconfig 2.2.0 
emmet 2.4.3 
file-icons 2.0.15 
git-plus 7.2.2 
japanese-word-selection 0.4.0 
language-apache 1.7.0 
language-jade 0.7.2 
linter 1.11.21 
linter-htmlhint 1.3.1 
linter-scss-lint 3.0.4 
minimap 4.26.8 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
monokai 0.20.0 
move-panes 0.2.0 
multi-cursor 2.1.5 
open-recent 5.0.0 
pigments 0.39.0 
project-manager 3.3.3 
regex-railroad-diagram 0.16.0 
stylefmt 4.0.0 
Sublime-Style-Column-Selection 1.7.3 
term3 0.22.1 
toggle-quotes 1.0.0 
trailing-spaces 0.4.0 
vim-mode 0.66.0 
vim-mode-plus 0.82.0 
vim-mode-visual-block 0.2.16 
```

**Comment by t9md** [comment]
Can you reproduce 100%? or is this occasional issue?
Pls give me info to reproduce, it's really helpful.

**Comment by ysakmrkm** [comment]
Sorry for blank the step.

It's reproduce 100%.

1. ctrl+v (visual block mode)
2. move cursor up or down
3. p or P

I want to paste text, but this is wrong way i know (need to esc before step 3)

**Comment by t9md** [comment]
thanks, confirmed this is the degradation introduced in v0.80.0.
Will fix.

**Comment by t9md** [comment]
regression happens in this commit

https://github.com/t9md/atom-vim-mode-plus/commit/26c41d989b69a8165da5dae5492360178b98fc62

**Comment by t9md** [comment]
v0.82.1 is out

**Comment by ZuBB** [comment]
today got this. is it really closed?
