### ISSUE TITLE
Uncaught TypeError: patch.getChanges is not a function

### ISSUE THREAD

**Issue by ashishsc** [t9md/atom-vim-mode-plus#686]
[Enter steps to reproduce:]

1. Press escape (exit insert mode)

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.82.3

### Stack Trace

Uncaught TypeError: patch.getChanges is not a function

```
At /home/ashish/.atom/packages/vim-mode-plus/lib/utils.coffee:144

TypeError: patch.getChanges is not a function
    at getNewTextRangeFromCheckpoint (/packages/vim-mode-plus/lib/utils.coffee:144:45)
    at /packages/vim-mode-plus/lib/operator.coffee:1126:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at ModeManager.deactivate (/packages/vim-mode-plus/lib/mode-manager.coffee:71:14)
    at ModeManager.activate (/packages/vim-mode-plus/lib/mode-manager.coffee:51:6)
    at /packages/vim-mode-plus/node_modules/delegato/lib/delegator.js:67:61)
    at /packages/vim-mode-plus/lib/main.coffee:145:35)
    at /packages/vim-mode-plus/lib/main.coffee:182:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -0:26 vim-mode-plus:move-down (input.hidden-input)
     -0:23.6.0 vim-mode-plus:move-to-next-word (input.hidden-input)
  2x -0:22 vim-mode-plus:move-to-end-of-word (input.hidden-input)
  6x -0:18.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:17.9.0 vim-mode-plus:move-right (input.hidden-input)
  9x -0:17.6.0 vim-mode-plus:move-down (input.hidden-input)
     -0:11.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:11.2.0 vim-mode-plus:move-down (input.hidden-input)
     -0:10.8.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
  2x -0:08.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
 17x -0:08.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:08.3.0 vim-mode-plus:delete (input.hidden-input)
  4x -0:06.4.0 vim-mode-plus:move-up (input.hidden-input)
     -0:03.2.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:02.8.0 editor:newline (input.hidden-input)
  2x -0:00.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 0.6.6 
elm-format 2.1.0 
elmjutsu 5.2.0 
ex-mode 0.13.0 
haskell-ghc-mod 1.17.2 
haskell-hoogle 0.1.3 
language-elm 1.5.0 
language-haskell 1.9.7 
linter 1.11.16 
linter-elm-make 0.17.3 
linter-hlint 0.5.0 
vim-mode-plus 0.82.3 
```

**Comment by t9md** [comment]
You can always 100% reproduce this, or occasional issue?

**Comment by ashishsc** [comment]
100% of the time

**Comment by ashishsc** [comment]
Noticed this too:
https://github.com/atom/vim-mode/issues/989

**Comment by t9md** [comment]
So you cannot use vim-mode-plus anymore right? Have you worked before? Can you say when it's began to broke?
Since I'm macOS user and have no issue with same version of Atom and vim-mode-plus with yours.

**Comment by t9md** [comment]
vim-mode 's issue is not relevant, and the error you reported is very strange.
Since stacktrace include `utils.coffee:144` but `patch.getChanges` code is no longer exists in latest version.  it was there in very old version like this

https://github.com/t9md/atom-vim-mode-plus/blob/v0.44.0/lib/utils.coffee

But no longer.
Have you update vim-mode-plus recently and restarted after that?
Do you really use latest vim-mode-plus?
re-installing it solve your problem? 

- `apm uninstall vim-mode-plus`
- `apm install vim-mode-plus`

**Comment by t9md** [comment]
Why I think clean removal/install solve problem
- Some what relevant https://github.com/t9md/atom-vim-mode-plus/issues/679
- Maybe partial install( because of update failure i don't know ) cause didn't refresh old file reference in `asar` package archive.

I believe this is not vim-mode-plus specific issue.

**Comment by subos2008** [comment]
I just started seeing this today.
