### ISSUE TITLE
Trying to use visual mode after upgrade gives a TypeError

### ISSUE THREAD

**Issue by nemith** [t9md/atom-vim-mode-plus#705]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: "Fedora release
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.84.1

### Stack Trace

Uncaught TypeError: Cannot read property 'locator' of null

```
At /home/bbennett/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:122

TypeError: Cannot read property 'locator' of null
  at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:103:20)
  at /packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:222:18
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at TextEditor.module.exports.TextEditor.cursorMoved (/app.asar/src/text-editor.js:2126:27)
  at Selection.module.exports.Selection.markerDidChange (/app.asar/src/selection.js:921:21)
  at /app.asar/src/selection.js:41:24
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
  at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
  at Marker.module.exports.Marker.update (/app.asar/node_modules/text-buffer/lib/marker.js:362:12)
  at Marker.module.exports.Marker.setRange (/app.asar/node_modules/text-buffer/lib/marker.js:104:19)
  at DisplayMarker.module.exports.DisplayMarker.setBufferRange (/app.asar/node_modules/text-buffer/lib/display-marker.js:134:32)
  at /app.asar/src/selection.js:107:24
  at Selection.module.exports.Selection.modifySelection (/app.asar/src/selection.js:972:7)
  at Selection.module.exports.Selection.setBufferRange (/app.asar/src/selection.js:100:19)
  at SelectionWrapper.setBufferRange (/packages/vim-mode-plus/lib/selection-wrapper.coffee:209:16)
  at SelectionWrapper.translateSelectionEndAndClip (/packages/vim-mode-plus/lib/selection-wrapper.coffee:228:6)
  at MoveDown.Motion.selectByMotion (/packages/vim-mode-plus/lib/motion.coffee:143:22)
  at MoveDown.Motion.select (/packages/vim-mode-plus/lib/motion.coffee:105:8)
  at MoveDown.Motion.execute (/packages/vim-mode-plus/lib/motion.coffee:98:8)
  at Select.Operator.selectTarget (/packages/vim-mode-plus/lib/operator.coffee:275:13)
  at /packages/vim-mode-plus/lib/operator.coffee:234:9
  at NuclideTextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:818:18)
  at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1589:26)
  at Select.Operator.startMutation (/packages/vim-mode-plus/lib/operator.coffee:233:15)
  at Select.execute (/packages/vim-mode-plus/lib/operator.coffee:325:6)
  at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.coffee:153:27)
  at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.coffee:142:8)
  at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.coffee:85:10)
  at /packages/vim-mode-plus/lib/base.coffee:322:7)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
  at /app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
  at /app.asar/src/window-event-handler.js:3:59)

```

### Commands

```
     -0:44.2.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  4x -0:44 vim-mode-plus:move-down (input.hidden-input)
  3x -0:42 vim-mode-plus:move-up (input.hidden-input)
     -0:12.7.0 vim-mode-plus:repeat-find-reverse (input.hidden-input)
     -0:11.3.0 vim-mode-plus:move-down (input.hidden-input)
  5x -0:10.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:09.9.0 vim-mode-plus:move-down (input.hidden-input)
     -0:09.6.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  3x -0:09.3.0 vim-mode-plus:move-down (input.hidden-input)
     -0:08.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:07.6.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  6x -0:05.6.0 vim-mode-plus:delete (input.hidden-input)
  2x -0:03.9.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:03.3.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-dlang 1.1.2 
go-debug 1.2.0 
go-plus 5.3.4 
go-signature-statusbar 1.2.0 
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.57.0 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
nuclide 0.211.53192568 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 0.84.1 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by t9md** [comment]
How to repro? Can you reproduce 100% always?

Your error the `locator` is not property provided by vim-mode-plus.
`GoSignatureStatusbarView.displaySignature` seems to be related.
How about reporting `go-signature-statusbar` package issue?

**Comment by t9md** [comment]
I don't thinks this is vmp issue, so close.
