### ISSUE TITLE
Uncaught TypeError: Cannot set property 'isDirty' of undefined

### ISSUE THREAD

**Issue by 0bman** [t9md/atom-vim-mode-plus#714]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.84.1

### Stack Trace

Uncaught TypeError: Cannot set property 'isDirty' of undefined

```
At /Users/vova/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:122

TypeError: Cannot set property 'isDirty' of undefined
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:262:23
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:679:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:663:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:16)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:821:14)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1589:26)
    at Delete.Operator.startMutation (/packages/vim-mode-plus/lib/operator.coffee:233:15)
    at Delete.Operator.execute (/packages/vim-mode-plus/lib/operator.coffee:241:6)
    at Delete.execute (/packages/vim-mode-plus/lib/operator.coffee:449:5)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.coffee:153:27)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.coffee:142:8)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.coffee:85:10)
    at /packages/vim-mode-plus/lib/base.coffee:325:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:26.7.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:25.9.0 vim-mode-plus:delete (input.hidden-input)
     -0:21.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:19.7.0 vim-mode-plus:move-up (input.hidden-input)
     -0:19.4.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:19.1.0 vim-mode-plus:delete (input.hidden-input)
     -0:15.5.0 pane:show-next-item (input.hidden-input)
     -0:14.6.0 core:close (input.hidden-input)
  3x -0:14 vim-mode-plus:move-up (input.hidden-input)
     -0:13.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:13 vim-mode-plus:move-up (input.hidden-input)
     -0:12.9.0 vim-mode-plus:delete (input.hidden-input)
     -0:12.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:12 vim-mode-plus:move-down (input.hidden-input)
  2x -0:11.8.0 vim-mode-plus:delete (input.hidden-input)
     -0:10 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
autoclose-html 0.23.0 
autocomplete-modules 1.6.8 
blame 0.10.2 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.3 
double-tag 0.7.0 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
ex-mode 0.14.0 
expose 0.14.0 
file-icons 2.1.1 
gemsource 0.3.0 
git-time-machine 1.5.6 
indent-guide-improved 1.4.12 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.57.1 
language-haml 0.24.1 
language-nginx 0.7.0 
language-slim 0.5.0 
linter 2.1.2 
linter-eslint 8.1.4 
linter-rubocop 1.1.1 
linter-stylelint 3.9.0 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
nuclide 0.211.0 
pigments 0.39.1 
qolor 0.4.1 
rails-i18n-autocomplete 0.4.0 
rails-transporter 1.6.5 
railscast-theme 0.3.0 
react 0.16.2 
recent-files-fuzzy-finder 0.3.1 
ruby-block-converter 3.5.0 
sort-lines 0.14.0 
sync-settings 0.8.1 
todo-show 1.11.0 
trailing-spaces 0.4.0 
vim-mode-plus 0.84.1 
wakatime 6.0.13 
Zen 0.16.4 
```

**Comment by t9md** [comment]
Although who threw exception is vim-mode-plus, actual error happened in tern.js.

Read the stacktrace you pasted.
```
TypeError: Cannot set property 'isDirty' of undefined
    at /packages/atom-ternjs/lib/atom-ternjs-manager.js:262:23
```

`isDirty` is not vmp's identifier, it's must be tern.js's one.
Open issue on tern.js with how to reproduce information.
