### ISSUE TITLE
Uncaught Error: Assertion failed: attempted to normalize but no properties to restore

### ISSUE THREAD

**Issue by lumio** [t9md/atom-vim-mode-plus#716]
1. Using color-picker on existing color with CMD+Shift+C
2. Press escape

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.85.0

### Stack Trace

Uncaught Error: Assertion failed: attempted to normalize but no properties to restore

```
At /Users/lumio/.atom/packages/vim-mode-plus/lib/utils.coffee:15

Error: Assertion failed: attempted to normalize but no properties to restore
    at /packages/vim-mode-plus/lib/utils.coffee:15:15
    at AtomEnvironment.module.exports.AtomEnvironment.assert (/app.asar/src/atom-environment.js:969:13)
    at assertWithException (/packages/vim-mode-plus/lib/utils.coffee:14:8)
    at SelectionWrapper.normalize (/packages/vim-mode-plus/lib/selection-wrapper.coffee:166:5)
    at Function.swrap.normalize (/packages/vim-mode-plus/lib/selection-wrapper.coffee:201:18)
    at Disposable.disposalAction (/packages/vim-mode-plus/lib/mode-manager.coffee:168:13)
    at Disposable.module.exports.Disposable.dispose (/app.asar/node_modules/event-kit/lib/disposable.js:24:16)
    at ModeManager.deactivate (/packages/vim-mode-plus/lib/mode-manager.coffee:76:21)
    at ModeManager.activate (/packages/vim-mode-plus/lib/mode-manager.coffee:45:6)
    at /packages/vim-mode-plus/node_modules/delegato/lib/delegator.js:67:61)
    at /packages/vim-mode-plus/lib/main.coffee:156:35)
    at /packages/vim-mode-plus/lib/main.coffee:200:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:19 color-picker:open (input.hidden-input)
     -0:17.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:10 core:undo (input.hidden-input)
     -0:07.7.0 color-picker:open (input.hidden-input)
  2x -0:06.9.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-typescript 11.0.1 
autocomplete-html-entities 0.1.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.6.8 
busy-signal 1.3.0 
color-picker 2.2.5 
custom-title 1.0.1 
editorconfig 2.2.2 
foldername-tabs 0.2.4 
git-plus 7.3.3 
intentions 1.1.2 
language-liquid 0.5.1 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.1 
react 0.16.2 
relative-numbers 0.7.1 
vim-mode-plus 0.85.0 
```

**Comment by t9md** [comment]
Thanks for reporting, not perfect solution, but no longer throw exception.
try v0.86.2.
If you still issue see issue reopen this.
