### ISSUE TITLE
Numbered tab navigation - [1...n]gt 

### ISSUE THREAD

**Issue by akeelm** [t9md/atom-vim-mode-plus#759]
I quite often use the numbered tab navigation in Vim, where you can say press 3gt to navigate to the third tab.

**Comment by akeelm** [comment]
I quite often use the numbered tab navigation in Vim, where you can say press 3gt to go to the third open tab.

I've had a play about with this and am able to implement this feature by editing the code for the plugin as downloaded from the atom packages. However, when cloning from the repository directly, the plugin doesn't work and even after running "npm install" I'm confronted with the following error:


TypeError: this.markerLayer.clear is not a function
    at MutationManager.module.exports.MutationManager.reset (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/mutation-manager.coffee:24:18)
    at VimState.module.exports.VimState.reset (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/vim-state.coffee:285:22)
    at ModeManager.activateNormalMode (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/mode-manager.coffee:85:15)
    at ModeManager.<anonymous> (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/mode-manager.coffee:48:27)
    at ModeManager.activate (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/mode-manager.coffee:47:20)
    at VimState._results.push._this.(anonymous function) [as activate] (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/node_modules/delegato/lib/delegator.js:67:61)
    at new VimState (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/vim-state.coffee:79:8)
    at /home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/main.coffee:43:22
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:329:9)
    at Object.activate (/home/akeel/.atom/dev/packages/atom-vim-mode-plus/lib/main.coffee:41:31)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:19)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:548:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:524:19)u're 
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:506:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:792:28


I'd love to contribute my solution if you're interested.

Thanks,
Akeel

**Comment by t9md** [comment]
Not sure you error is, I implement that feature, you can check how to enhance vmp with the linked PR.
