### ISSUE TITLE
Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

### ISSUE THREAD

**Issue by bronson** [t9md/atom-vim-mode-plus#76]
Not quite sure how this happened...  I think it was while undoing a few changes in a coffeescript file.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:30

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1186:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2082:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2064:35)
    at TextEditor.module.exports.TextEditor.undo (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1184:12)
    at Undo.mutate (/Users/bronson/.atom/packages/vim-mode-plus/lib/misc-commands.coffee:109:13)
    at Undo.mutateWithTrackingChanges (/Users/bronson/.atom/packages/vim-mode-plus/lib/misc-commands.coffee:70:6)
    at Undo.execute (/Users/bronson/.atom/packages/vim-mode-plus/lib/misc-commands.coffee:98:6)
    at OperationStack.process (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:80:8)
    at OperationStack.run (/Users/bronson/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:27:8)
    at run (/Users/bronson/.atom/packages/vim-mode-plus/lib/base.coffee:12:27)
    at atom-text-editor.<anonymous> (/Users/bronson/.atom/packages/vim-mode-plus/lib/base.coffee:153:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:31.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -1:29.6.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:27.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:26.6.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:26.4.0 vim-mode-plus:replace (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:26.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:26.1.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:25.4.0 vim-mode-plus:replace (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:24.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:24.7.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode)
     -0:24.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:23.8.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:08.5.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.9.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.operator-pending-mode)
  3x -0:07.7.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -0:01.9.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "exception-reporting",
      "welcome",
      "background-tips"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-reef-syntax"
    ],
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "rspec",
      "ruby-test-switcher",
      "rails-transporter"
    ]
  },
  "vim-mode-plus": {
    "incrementalSearch": true,
    "setCursorToStartOfChangeOnUndoRedo": true,
    "flashOnUndoRedo": true,
    "flashOnUndoRedoDuration": 300
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.13.0
atom-ternjs, v0.12.1
color-picker, v2.0.14
cursor-history, v0.5.9
file-icons, v1.6.13
highlight-selected, v0.11.1
language-haml, v0.23.14
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-erb, v0.1.1
linter-eslint, v5.2.6
linter-haml, v1.0.0
linter-jscs, v3.2.0
linter-ruby, v1.2.0
linter-tidy, v1.0.1
oceanic-reef-syntax, v0.6.0
project-find-navigation, v0.0.9
react, v0.12.10
ruby-test-switcher, v1.2.0
vim-mode-plus, v0.9.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Yes mee too suffering from this issue.
I think it somehow related on update done in Atom v1.3.0?.
Although I haven't investigate yet, my impression is not vim-mode-plus specific bug.

**Comment by t9md** [comment]
Need to read
https://github.com/atom/atom/issues/9918

**Comment by bronson** [comment]
Oof, that's a lot of reports.  At least we're not alone!

**Comment by t9md** [comment]
From Atom v1.3.3 release this error should be fixed.
