### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateSync' of null

### ISSUE THREAD

**Issue by norderik** [t9md/atom-vim-mode-plus#773]
[Enter steps to reproduce:]

1. In editor press Ctrl-- or Ctrl-+ to change zoom size

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Windows 10
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.91.0

### Stack Trace

Uncaught TypeError: Cannot read property 'updateSync' of null

```
At C:\Users\me\.atom\packages\vim-mode-plus\lib\cursor-style-manager.coffee:44

TypeError: Cannot read property 'updateSync' of null
    at CursorStyleManager.refresh (/packages/vim-mode-plus/lib/cursor-style-manager.coffee:44:29)
    at /packages/vim-mode-plus/lib/cursor-style-manager.coffee:1:1
    at /app.asar/src/config.js:618:16
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Workspace.decreaseFontSize (/app.asar/src/workspace.js:946:19)
    at /app.asar/src/register-default-commands.js:64:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:13.8.0 intentions:highlight (input.hidden-input)
     -4:13.7.0 vim-mode-plus:scroll-full-screen-up (input.hidden-input)
  6x -4:12.3.0 vim-mode-plus:move-up (input.hidden-input)
  2x -4:11 vim-mode-plus:move-to-next-word (input.hidden-input)
  2x -4:10.3.0 vim-mode-plus:delete-right (input.hidden-input)
     -4:09.8.0 intentions:highlight (input.hidden-input)
     -4:09.6.0 core:save (input.hidden-input)
     -4:08.4.0 vim-mode-plus:move-to-mark-line (input.hidden-input)
     -4:08.2.0 vim-mode-plus:set-input-char-' (input.hidden-input)
  2x -4:05.7.0 vim-mode-plus:move-down (input.hidden-input)
     -4:01.5.0 intentions:highlight (input.hidden-input)
     -4:01.2.0 core:save (input.hidden-input)
  8x -0:46.4.0 intentions:highlight (input.hidden-input)
  2x -0:45.7.0 window:reset-font-size (input.hidden-input)
     -0:39.2.0 intentions:highlight (input.hidden-input)
     -0:38.8.0 window:decrease-font-size (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.3 
busy-signal 1.4.1 
intentions 1.1.2 
language-typoscript 0.1.0 
linter 2.1.4 
linter-tslint 1.3.0 
linter-ui-default 1.2.3 
minimap 4.28.1 
project-manager 3.3.4 
remote-sync 4.1.5 
typo3-fluid-atom-snippets 1.2.0 
typo3-fluid-snippets 0.1.0 
vim-mode-plus 0.91.0 
```

**Comment by t9md** [comment]
Can you reproduce this always? Or occasional issue? I don't have windows so want to know more detailed info and condition to make me understand issue correctly.

**Comment by norderik** [comment]
Just restarted atom and the problem did not occur again. Since windows 10 has some issues when put to hibernation several times, I think this was the reason for this behaviour.

**Comment by t9md** [comment]
OK. Understood. thanks.
