### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by rafi** [t9md/atom-vim-mode-plus#780]
1. Run Atom beta
2. Open a few splits
3. Close splits

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.91.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:340

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:340:28)
    at /packages/vim-mode-plus/lib/motion.coffee:792:48)
    at Tween.run (/packages/save-session/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6194:22)
    at tick (/packages/save-session/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6561:31)
    at jQuery.fx.tick (/packages/save-session/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:6858:9)
```

### Commands

```
 12x -1:27 core:move-up (div.tool-panel.tree-view)
     -1:26.5.0 tree-view:toggle (div.tool-panel.tree-view)
  3x -1:26.5.0 blur (div.tool-panel.tree-view)
  5x -1:26 vim-mode-plus:move-down (input.hidden-input)
 20x -1:25.7.0 vim-mode-plus:move-up (input.hidden-input)
 36x -1:24.6.0 vim-mode-plus:scroll-half-screen-up (input.hidden-input)
     -1:23.4.0 pane:close (input.hidden-input)
 20x -1:23.4.0 blur (input.hidden-input)
     -1:07.5.0 core:close (input.hidden-input)
 10x -1:07.5.0 blur (input.hidden-input)
     -1:07.1.0 core:close (input.hidden-input)
  7x -1:07.1.0 blur (input.hidden-input)
     -1:02.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-gruvbox-syntax.theme-one-dark-ui)
 11x -1:02.8.0 blur (div.deprecation-cop-status.inline-block.text-warning)
     -0:33.7.0 settings-view:open (div.deprecation-cop.pane-item.native-key-bindings)
 18x -0:33.6.0 blur (div.deprecation-cop.pane-item.native-key-bindings)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
blessed-dark-syntax 0.3.0 
busy-signal 1.4.1 
choose-pane 0.7.0 
cursor-history 0.10.1 
dark-flat-ui 1.2.4 
docblockr 0.9.4 
duotone-dark-syntax 2.1.0 
eclectic-syntax 0.2.1 
expose 0.14.0 
file-icons 2.1.4 
firewatch-syntax 1.1.1 
focus-pane-or-panel 0.3.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-time-machine 1.5.9 
gruvbox-syntax 2.4.1 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.3.0 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
one-dark-vivid-syntax 1.7.1 
paner 0.4.0 
pigments 0.39.1 
project-find-navigation 0.4.0 
project-manager 3.3.4 
recent-finder 0.5.1 
save-session 0.15.7 
todo-show 1.11.0 
twilight 0.3.0 
twilight-syntax 0.8.0 
vim-mode 0.66.0 
vim-mode-plus 0.91.0 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by t9md** [comment]
Thanks,  I could reproduce.

1. enable `smoothScrollOnHalfScrollMotion` or `smoothScrollOnFullScrollMotion`
2. Do smooth scroll
3. Immediately close pane by `cmd-w` while smooth scroll is NOT yet finished.

**Comment by t9md** [comment]
Released
