### ISSUE TITLE
Uncaught Error: Assertion failed: trying to reverse selection which is non-empty and property-lesss

### ISSUE THREAD

**Issue by khiem-nguyen** [t9md/atom-vim-mode-plus#783]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.92.1

### Stack Trace

Uncaught Error: Assertion failed: trying to reverse selection which is non-empty and property-lesss

```
At /Users/khiem-nguyen/.atom/packages/vim-mode-plus/lib/utils.coffee:9

Error: Assertion failed: trying to reverse selection which is non-empty and property-lesss
    at /packages/vim-mode-plus/lib/utils.coffee:9:15
    at AtomEnvironment.module.exports.AtomEnvironment.assert (/app.asar/src/atom-environment.js:983:13)
    at assertWithException (/packages/vim-mode-plus/lib/utils.coffee:8:8)
    at SelectionWrapper.setReversedState (/packages/vim-mode-plus/lib/selection-wrapper.coffee:56:5)
    at Function.swrap.setReversedState (/packages/vim-mode-plus/lib/selection-wrapper.coffee:194:14)
    at Disposable.disposalAction (/packages/vim-mode-plus/lib/mode-manager.coffee:173:15)
    at Disposable.module.exports.Disposable.dispose (/app.asar/node_modules/event-kit/lib/disposable.js:24:16)
    at ModeManager.deactivate (/packages/vim-mode-plus/lib/mode-manager.coffee:74:21)
    at ModeManager.activate (/packages/vim-mode-plus/lib/mode-manager.coffee:40:6)
    at /packages/vim-mode-plus/node_modules/delegato/lib/delegator.js:67:61)
    at VimState.module.exports.VimState.checkSelection (/packages/vim-mode-plus/lib/vim-state.coffee:250:8)
```

### Commands

```
     -0:40.5.0 core:confirm (input.hidden-input)
 11x -0:38.1.0 vim-mode-plus:move-down (input.hidden-input)
  3x -0:36.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:36.1.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
  8x -0:35.9.0 vim-mode-plus:move-down (input.hidden-input)
     -0:33.7.0 vim-mode-plus:move-up (input.hidden-input)
  2x -0:29.6.0 core:copy (input.hidden-input)
     -0:27.4.0 core:paste (input.hidden-input)
  8x -0:26.5.0 vim-mode-plus:move-up (input.hidden-input)
     -0:25 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
  8x -0:24.8.0 vim-mode-plus:move-down (input.hidden-input)
     -0:21.6.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
  4x -0:20.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:19.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:15.2.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
  7x -0:14.6.0 vim-mode-plus:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-monokai 0.10.9 
busy-signal 1.4.1 
goto-definition 1.3.3 
intentions 1.1.2 
linter 2.1.4 
linter-jsonlint 1.3.0 
linter-python 3.1.1 
linter-ruby 1.2.5 
linter-ui-default 1.2.4 
monokai 0.24.0 
native-ui 0.20.6 
nucleus-dark-ui 0.12.1 
platformio-ide-terminal 2.5.0 
seti-ui 1.8.0 
vim-mode 0.66.0 
vim-mode-plus 0.92.1 
```

**Comment by t9md** [comment]
This error no longer happens since I removed this assertion(because it's wrong, lack of my understanding).
