### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tail' of undefined

### ISSUE THREAD

**Issue by cmavromoustakos** [t9md/atom-vim-mode-plus#805]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.93.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tail' of undefined

```
At /Users/cmavromoustakos/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:130

TypeError: Cannot read property 'tail' of undefined
    at BlockwiseSelection.getProperties (/packages/vim-mode-plus/lib/blockwise-selection.coffee:112:55)
    at BlockwiseSelection.normalize (/packages/vim-mode-plus/lib/blockwise-selection.coffee:187:19)
    at Function.swrap.normalize (/packages/vim-mode-plus/lib/selection-wrapper.coffee:213:26)
    at Select.Operator.normalizeSelectionsIfNecessary (/packages/vim-mode-plus/lib/operator.coffee:200:14)
    at Select.Operator.startMutation (/packages/vim-mode-plus/lib/operator.coffee:211:8)
    at Select.execute (/packages/vim-mode-plus/lib/operator.coffee:299:6)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.coffee:160:27)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.coffee:150:8)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.coffee:89:12)
    at /packages/vim-mode-plus/lib/base.coffee:368:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -0:18.3.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:16.7.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
     -0:16.4.0 vim-mode-plus:move-down (input.hidden-input)
     -0:15.1.0 vim-mode-plus:change (input.hidden-input)
     -0:14.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:13.9.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:12.8.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
     -0:12.6.0 vim-mode-plus:move-down (input.hidden-input)
     -0:11.5.0 vim-mode-plus:change (input.hidden-input)
     -0:10.3.0 core:backspace (input.hidden-input)
     -0:09.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:09.0 vim-mode-plus:move-down (input.hidden-input)
  6x -0:08.4.0 vim-mode-plus:move-left (input.hidden-input)
     -0:06.6.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
  2x -0:06.4.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:05.6.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
vim-mode-plus 0.93.0 
```

**Comment by t9md** [comment]
This is bug, but how to reproduce? what is your operation when issue happened.

**Comment by cmavromoustakos** [comment]
I was trying to highlight a block of text and indent.
