### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by canxer314** [t9md/atom-vim-mode-plus#832]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.97.2

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of null

```
At C:\Users\ecidi\.atom\packages\vim-mode-plus\lib\register-manager.js:35

TypeError: Cannot read property 'forEach' of null
    at RegisterManager.destroy (/packages/vim-mode-plus/lib/register-manager.js:35:33)
    at RegisterManager.vimState.onDidDestroy (/packages/vim-mode-plus/lib/register-manager.js:26:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at VimState.destroy (/packages/vim-mode-plus/lib/vim-state.js:351:18)
    at VimState.editor.onDidDestroy (/packages/vim-mode-plus/lib/vim-state.js:152:41)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor.js:660:26)
    at TextEditor.module.exports.Model.destroy (~/AppData/Local/atom/app-1.19.1/resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:707:66)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
  4x -7:23.1.0 vim-mode-plus:move-down (input.hidden-input)
     -7:21.1.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -7:20.6.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
     -7:20.2.0 vim-mode-plus:move-right (input.hidden-input)
  2x -7:20 vim-mode-plus:move-down (input.hidden-input)
     -7:19.4.0 vim-mode-plus:move-up (input.hidden-input)
  4x -7:19.1.0 vim-mode-plus:move-left (input.hidden-input)
     -7:18.3.0 vim-mode-plus:move-right (input.hidden-input)
     -7:18 vim-mode-plus:delete (input.hidden-input)
     -7:17.9.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -7:17.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -7:16.9.0 vim-mode-plus:move-up (input.hidden-input)
     -7:16.3.0 vim-mode-plus:move-down (input.hidden-input)
     -7:15.4.0 intentions:highlight (input.hidden-input)
     -7:15.4.0 core:save (input.hidden-input)
  6x -4:12.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-react-autocomplete 0.1.10 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.6.10 
autocomplete-paths 2.8.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-snippets-compatibility 1.0.6 
ex-mode 0.17.0 
file-icons 2.1.10 
foldername-tabs 0.2.4 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.11.0 
language-babel 2.71.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-less 2.6.0 
linter-ui-default 1.6.5 
linter-write-good 0.9.0 
lodash-snippets 2.0.0 
markdown-preview-enhanced 0.14.7 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
pristine-ui 1.1.6 
project-manager 3.3.5 
pure-syntax 0.3.0 
react-es6-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-snippets 0.9.0 
sync-settings 0.8.2 
vim-mode-plus 0.97.2 
```

**Comment by t9md** [comment]
can you reproduce always?
How to reproduce?
What did you do when issue happened.

**Comment by canxer314** [comment]
I don't know to how to reproduce this, I just remember I closing some tabs in the tabbar so fast, and then the exception threw

**Comment by t9md** [comment]
thanks!

**Comment by t9md** [comment]
I tried, but couldn't reproduce. Will keep open for a while.
Why I don't immediately try to fix the code shown on stacktrace is because I can't understand why this happens.

That stackTrace says `subscriptionBySelection` is `null` in `destroy()`, but I cannot imagine the code-flow where this become `null`.
Maybe because of my lack of understanding of JavaScript, will see.

**Comment by t9md** [comment]
Close.
Not-resolved
Want to let user re-open issue if this is still issue.
