### ISSUE TITLE
Uncaught TypeError: Cannot read property 'refs' of undefined

### ISSUE THREAD

**Issue by tjcarskadon** [t9md/atom-vim-mode-plus#841]
[Enter steps to reproduce:]

1. The error happens when trying to `yank` to something with `yt` or when trying to navigate with `t` or `f` In normal mode. 

Just started today and this is gonna be a bummer until it gets fixed

Let me know if you have questions

**Atom**: 1.20.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.98.0

### Stack Trace

Uncaught TypeError: Cannot read property 'refs' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1455

TypeError: Cannot read property 'refs' of undefined
    at TextEditorComponent.didFocus (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1455:58)
    at HTMLElement.addEventListener (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:36:67)
    at focusInput (/packages/vim-mode-plus/lib/focus-input.js:46:18)
    at VimState.focusInput (/packages/vim-mode-plus/lib/vim-state.js:581:5)
    at Till.Base.focusInput (/packages/vim-mode-plus/lib/base.coffee:170:15)
    at Till.Find.initialize (/packages/vim-mode-plus/lib/motion.coffee:872:6)
    at /packages/vim-mode-plus/lib/motion.coffee:48:6)
    at /packages/vim-mode-plus/lib/motion.coffee:863:7)
    at /packages/vim-mode-plus/lib/motion.coffee:906:7)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.js:101:23)
    at /packages/vim-mode-plus/lib/base.coffee:375:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:602:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:460:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:26.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:12.2.0 vim-mode-plus:move-up (input.hidden-input)
     -0:11.7.0 vim-mode-plus:move-down (input.hidden-input)
     -0:10.3.0 vim-mode-plus:yank (input.hidden-input)
     -0:09.1.0 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:09.0 vim-mode-plus:set-input-char-t (input.hidden-input)
     -0:07.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:07.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:07.2.0 vim-mode-plus:move-down (input.hidden-input)
     -0:05.3.0 vim-mode-plus:yank (input.hidden-input)
     -0:05.3.0 vim-mode-plus:till (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-clock 0.1.13 
atom-keyboard-macros-vim 0.1.6 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 1.7.0 
autocomplete-python 1.10.2 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
choose-pane 0.7.0 
clipboard-plus 0.5.1 
cursor-blink-interval 0.3.1 
cursor-history 0.12.0 
easy-motion-redux 1.1.1 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.11 
git-plus 7.9.3 
goto-definition 1.3.4 
hey-pane 1.0.0 
highlight-selected 0.13.1 
imdone-atom 2.2.6 
intentions 1.1.5 
jsonlint 1.1.4 
kite 0.37.0 
language-babel 2.72.0 
language-graphql 0.9.0 
language-markdown 0.25.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-pylint 2.1.0 
linter-ui-default 1.6.7 
markdown-preview-plus 2.4.10 
move-panes 0.2.0 
oceanic-next 1.0.0 
open-in-browser 0.5.2 
open-this 0.4.0 
pigments 0.40.2 
platformio-ide-terminal undefined 
project-manager 3.3.5 
relative-numbers 0.8.0 
sort-lines 0.14.0 
tabs-to-spaces 1.0.3 
todo-show 2.0.0 
toggle 0.5.1 
trailing-semicolon 1.1.0 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 0.98.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-move-selected-text 0.10.0 
vim-mode-plus-subword-movement 0.2.2 
```

**Comment by t9md** [comment]
I'm using macOS with Atom 1.20.0-beta3 and have no issue.
Can you ugrade Atom-beta to beta3?

**Comment by t9md** [comment]
btw you don't need `vim-mode-plus-subword-movement` since it's now bundled in vim-mode-plus.

**Comment by tjcarskadon** [comment]
Well, that was odd because I thought I was on beta3 but I just upgraded to beta4 and all seems fine now.  

Noted on the old package, I'll pull it thanks for the super fast response and for the great package!!

**Comment by kurtharriger** [comment]
I encountered this issue on the atom stable release channel.  
It does work if I install the latest atom beta release.  I'm not sure how plugins define when to upgrade and which release of atom is required, but ideally this shouldn't auto update for users on atom stable release channel.

**Comment by kjad** [comment]
I was receiving this error when on Atom 1.19.1, upgraded to 1.19.3 and all good now

**Comment by kurtharriger** [comment]
Strange I did a check for updates in atom and it said there was none, I was on 1.19.0. Ran update check again and now its downloading an update.

**Comment by CodeCorrupt** [comment]
I also received this error when trying to `r <char to replace with>`

**Comment by t9md** [comment]
**Upgrade atom to the latest version(whichever stable or beta is OK)**

If there is someone who can not solve **after** upgrade Atom to the latest stable or beta version, let me know with the version and repro steps, I'll investigate.

For others, it's upstream Atom-core issue, I have nothing to do with this issue.
Although my understanding for this issue is basically Atom-core issue, this issue was not reported before vim-mode-plus version 0.98.0.
Why? because from v0.98.0 vim-mode-plus read user-input for (`r`, `f`, `surround`) via mini-editor(#838) instead of previous hacky way.

**Comment by CodeCorrupt** [comment]
Atom Version: 1.19.0
vim-mode-plus Version: 0.98.0

I still have the issue when replacing a char: `r <char to replace with>`

**Comment by t9md** [comment]
@CodeCorrupt Hey, can remove your commend if you read my above comment.

**Comment by willthemoor** [comment]
Was getting this error again after upgrading to VMP v1.16.0 on Atom 1.20.0-beta2 with `c t X` or `d f X`, etc. Upgraded Atom to 1.24.0-beta3 and no longer get the errors.
