### ISSUE TITLE
`this.cancel is not a function` using numbered registers

### ISSUE THREAD

**Issue by calebmeyer** [t9md/atom-vim-mode-plus#844]
Steps to reproduce:
1. Attempt to do any operation using a numeric register, like `"0p"` or `"1dw`

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.98.0

### Stack Trace

Uncaught TypeError: this.cancel is not a function

```
At C:\Users\CM022291\.atom\packages\vim-mode-plus\lib\register-manager.js:171

TypeError: this.cancel is not a function
    at onConfirm (/packages/vim-mode-plus/lib/register-manager.js:171:21)
    at CompositeDisposable.onDidSetInputChar.char (/packages/vim-mode-plus/lib/vim-state.js:593:9)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at VimState.emitDidSetInputChar (/packages/vim-mode-plus/lib/vim-state.js:332:18)
    at /packages/vim-mode-plus/lib/main.js:202:14)
    at /packages/vim-mode-plus/lib/main.js:215:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:38.6.0 vim-mode-plus:set-register-name (input.hidden-input)
     -0:38.3.0 vim-mode-plus:set-input-char-a (input.hidden-input)
     -0:37.6.0 vim-mode-plus:delete (input.hidden-input)
     -0:37.6.0 vim-mode-plus:move-to-next-word (input.hidden-input)
  4x -0:36.2.0 vim-mode-plus:move-left (input.hidden-input)
     -0:32.2.0 vim-mode-plus:yank (input.hidden-input)
     -0:32.2.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:30.7.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:29.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:26.9.0 vim-mode-plus:set-register-name (input.hidden-input)
     -0:26.3.0 vim-mode-plus:set-input-char-0 (input.hidden-input)
     -0:17.1.0 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:15.9.0 core:cancel (input.hidden-input)
     -0:15.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:12.1.0 vim-mode-plus:set-register-name (input.hidden-input)
     -0:11 vim-mode-plus:set-input-char-0 (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.5 
atom-runner 2.7.1 
auto-detect-indentation 1.3.0 
auto-update-plus 0.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
duotone-dark-amethyst-syntax 2.0.4 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-red-syntax 0.3.2 
duotone-dark-sea-syntax 2.1.0 
expand-region 0.3.1 
file-icons 2.1.11 
gist-it 0.9.2 
git-links 0.3.3 
git-plus 7.9.3 
git-time-machine 1.5.9 
intentions 1.1.5 
language-aspx 0.5.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-haml 0.25.1 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.7 
merge-conflicts 1.4.5 
minimap-plus 4.29.2 
monokai 0.24.0 
multi-wrap-guide 0.29.1 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
open-recent 5.0.0 
platformio-ide-terminal 2.5.5 
react 0.16.2 
rspec 0.4.0 
set-syntax 0.3.2 
spacemacs-dark-syntax 0.4.0 
symbol-gen 1.3.1 
sync-settings 0.8.2 
tabularize 0.2.5 
vim-mode-plus 0.98.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by t9md** [comment]
supporting numbered register is on https://github.com/t9md/atom-vim-mode-plus/issues/821.


Will fix not throwing exception when user attempted `"0y`.
