### ISSUE TITLE
Uncaught TypeError: Cannot read property 'operationStack' of undefined

### ISSUE THREAD

**Issue by bendavis78** [t9md/atom-vim-mode-plus#85]
I have the ctrl-w h/j/k/l bindings at the `body` scope, and when I go from term2 to the editor using <kbd>ctrl-w h</kbd>, the editor window closes and this error comes up.

**Atom Version**: 1.3.2
**System**: linux 4.2.6-9ph
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.10.2

### Stack Trace

Uncaught TypeError: Cannot read property 'operationStack' of undefined

```
At /home/ben/.atom/packages/vim-mode-plus/lib/base.coffee:12

TypeError: Cannot read property 'operationStack' of undefined
    at run (/home/ben/.atom/packages/vim-mode-plus/lib/base.coffee:12:11)
    at atom-text-editor.<anonymous> (/home/ben/.atom/packages/vim-mode-plus/lib/base.coffee:157:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.simulateBubblingOnDetachedTarget (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:561:23)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:538:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:510:14)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:386:23)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  4x -0:15.9.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:15.2.0 vim-mode-plus:move-to-first-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:15.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:14.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:14.3.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:09.3.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:09.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:08.0 window:focus-pane-on-left (div.terminal)
  2x -0:08.0 blur (div.terminal)
     -0:06.2.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.6.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  5x -0:02.3.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:01.3.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:00.6.0 core:close (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:00.6.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:00.6.0 vim-mode-plus:move-to-first-character-of-line-and-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-htmlhint",
      "minimap",
      "linter-polymer"
    ],
    "autoHideMenuBar": true
  },
  "vim-mode-plus": {}
}
```

### Installed Packages

```coffee
# User
gutter-shadow, v0.6.0
hidpi, v0.10.0
linter, v1.11.3
linter-jshint, v1.2.1
project-manager, v2.6.5
term2, v0.9.21
toggle-gutter, v0.2.2
vim-mode-plus, v0.10.2

# Dev
No dev packages
```

**Comment by t9md** [comment]
I could not reproduce issue(install term2 package).
Please give precise keystroke and where your cursor, buffer, pane-layout etc if  you know.

One diff in my environment is.
When I try to install term2, it fail to build so I patched [this PR](https://github.com/f/atom-term2/pull/211)

**Comment by t9md** [comment]
I added guard code to avoid this exception.
But I basically  don't want to add uncertain condition checking code scattered across codes.

So want to understand why this situation happens.
