### ISSUE TITLE
Uncaught TypeError: this.peekTop(...).setTarget is not a function

### ISSUE THREAD

**Issue by motjuste** [t9md/atom-vim-mode-plus#89]
I am not sure if the `f` command is supported 

1. Used the key `f<any letter>`

Nothing happens in the editor, the error is notified
The default `vim-mode` package notifies an error, but functions as expected (not tested extensively)

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.11.0

### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:43

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.process (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:57:20)
    at OperationStack.run (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:39:8)
    at run (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/base.coffee:158:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -0:30.9.0 vim-mode-plus:move-right (input.hidden-input)
     -0:30.4.0 vim-mode-plus:move-up (input.hidden-input)
 11x -0:30.4.0 vim-mode-plus:move-down (input.hidden-input)
 11x -0:28.6.0 vim-mode-plus:move-up (input.hidden-input)
  3x -0:28.1.0 vim-mode-plus:move-down (input.hidden-input)
     -0:25.8.0 vim-mode-plus:find (input.hidden-input)
  5x -0:25.8.0 blur (input.hidden-input)
     -0:25.7.0 vim-mode-plus:till (input.hidden-input)
  5x -0:25.7.0 blur (input.hidden-input)
     -0:23.7.0 vim-mode-plus:find (input.hidden-input)
  5x -0:23.7.0 blur (input.hidden-input)
     -0:23.6.0 vim-mode-plus:move-to-end-of-word (input.hidden-input)
  5x -0:07.1.0 blur (input.hidden-input)
     -0:02.0 vim-mode-plus:find (input.hidden-input)
  5x -0:02.0 blur (input.hidden-input)
     -0:01.9.0 vim-mode-plus:put-after (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tidy-markdown",
      "archive-view",
      "autocomplete-css",
      "markdown-preview",
      "linter-clang",
      "split-diff",
      "about",
      "incompatible-packages",
      "linter-pep8",
      "atom-beautify",
      "language-gfm",
      "linter-chktex",
      "vim-mode",
      "build-tools"
    ],
    "projectHome": "/Users/myrmidon/Delve/experiments",
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "wombat-dark-syntax"
    ]
  },
  "vim-mode-plus": {
    "useClipboardAsDefaultRegister": true,
    "startInInsertMode": true,
    "useSmartcaseForSearch": true,
    "showHoverOnOperate": true,
    "showHoverSearchCounter": true,
    "flashOnUndoRedo": true,
    "incrementalSearch": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.2.4
highlight-selected, v0.11.1
language-cmake, v0.1.4
language-gitignore, v0.2.0
language-latex, v0.6.1
language-matlab, v0.1.1
language-pfm, v0.82.0
language-swift, v0.4.0
linter, v1.11.3
linter-flake8, v1.9.3
linter-shellcheck, v1.0.2
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
pdf-view, v0.37.0
preview-inline, v0.5.1
set-syntax, v0.3.0
vim-mode-plus, v0.11.0
wombat-dark-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by motjuste** [comment]
Same error when using command `t<any letter>`

**Comment by t9md** [comment]
Yes, `f` is supported and works.

Try with simply Download and Install Atom from Web page
You seem to use homebrew-cask? and following PATH not fit your Atom version?
`opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)`

**Comment by motjuste** [comment]
- Yes, I was using homebrew-cask
- No, there is no directory `.../Resources/app.asar`
- There is a directory `.../Resources/app.asar.unpacked`, but there is no `src` directory in it.
- There is a file `.../Resources/app.asar`, which I have no idea how to open
- Same case when I installed atom from the atom.io website and checked the contents of `Atom.app`. Still face error.

May be this (currently open) [issue #701](https://github.com/atom/vim-mode/issues/701) for the same command (and others) when using the `vim-mode` package is related. 
All commands that are reported in the issue above for `vim-mode` package, also fail with *this* error when using `vim-mode-plus`

**Comment by t9md** [comment]
Oh, but

**Comment by t9md** [comment]
Ok, but I want make sure homebrew-cask is not related BEFORE investigating / patching this issue.
So please uninstall Atom from homebrew-cask and manually install Atom from web site.
Then reproduce issue.

In that case I believe stack trace not include any path like `Caskroom/atom/1.0.19/Atom.app`.

**Comment by motjuste** [comment]
I did uninstall the homebrew-cask one, deleted the old `~/.atom`, and installed atom from the website ... and installed all packages ala-fresh ... the first time I replied.

**BUT** after reading the comments of the referenced issue earlier ... I enabled `Use Shadow DOM` in settings, and **no more errors**. It also fixes the error in the `vim-mode` package. 

Stack trace when `Use Shadow DOM` is disabled.

***
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.11.0


### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:43

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.process (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:57:20)
    at OperationStack.run (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:39:8)
    at run (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/myrmidon/.atom/packages/vim-mode-plus/lib/base.coffee:158:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:04.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:02.1.0 vim-mode-plus:find (input.hidden-input)
  5x -0:02.1.0 blur (input.hidden-input)
     -0:02.0 vim-mode-plus:insert-after (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tidy-markdown",
      "archive-view",
      "autocomplete-css",
      "markdown-preview",
      "linter-clang",
      "split-diff",
      "about",
      "incompatible-packages",
      "linter-pep8",
      "atom-beautify",
      "language-gfm",
      "linter-chktex",
      "build-tools",
      "vim-mode"
    ],
    "projectHome": "/Users/myrmidon/Delve/experiments",
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "wombat-dark-syntax"
    ]
  },
  "vim-mode-plus": {
    "useClipboardAsDefaultRegister": true,
    "startInInsertMode": true,
    "useSmartcaseForSearch": true,
    "showHoverOnOperate": true,
    "showHoverSearchCounter": true,
    "flashOnUndoRedo": true,
    "incrementalSearch": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.2.4
highlight-selected, v0.11.1
language-cmake, v0.1.4
language-gitignore, v0.2.0
language-latex, v0.6.1
language-matlab, v0.1.1
language-pfm, v0.82.0
language-swift, v0.4.0
linter, v1.11.3
linter-flake8, v1.9.3
linter-shellcheck, v1.0.2
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
pdf-view, v0.37.0
preview-inline, v0.5.1
set-syntax, v0.3.0
vim-mode-plus, v0.11.0
wombat-dark-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for investigation.
Currently vim-mode-plus works properly when you enabled shadowDOM.
I'm not sure the situation you have to disable shadowDOM, any reason?

**Comment by motjuste** [comment]
I had it disabled. I don't remember if I did it, or was it that way by default. I do remember having some issues using Markdown preview with some theme installed a month ago, and trying a bunch of things. 

Anyway, it says that the option for Shadow DOM will be going away eventually. If it is going to be enabled by default, then this is a non-issue. 

Thanks for your quick replies. Hope I didn't waste your time. 

Best Wishes

**Comment by t9md** [comment]
ShadowDom should be enabled by default  in future so I wont care disabled situation.

Thanks

**Comment by crshd** [comment]
I still have this problem, both on 1.3.2 and 1.4.0-beta3, with ShadowDOM enabled.

--------------------

**Atom Version**: 1.4.0-beta3
**System**: Mac OS X 10.10.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.13.0


### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/mac07/etc/atom/packages/vim-mode-plus/lib/operation-stack.coffee:39

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.process (/Users/mac07/etc/atom/packages/vim-mode-plus/lib/operation-stack.coffee:53:20)
    at OperationStack.run (/Users/mac07/etc/atom/packages/vim-mode-plus/lib/operation-stack.coffee:35:8)
    at run (/Users/mac07/etc/atom/packages/vim-mode-plus/lib/base.coffee:14:29)
    at atom-text-editor.<anonymous> (/Users/mac07/etc/atom/packages/vim-mode-plus/lib/base.coffee:167:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:51.7.0 core:move-right (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  3x -2:51.3.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -2:49.2.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  2x -2:48.8.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -2:48.2.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:47.5.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -2:47.4.0 vim-mode-plus:yank (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  8x -2:36.3.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -1:00.1.0 settings-view:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
 13x -1:00.1.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:31 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:29.8.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:29.6.0 vim-mode-plus:replace (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
 16x -0:24.7.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.9.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.5.0 vim-mode-plus:substitute (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "imdone-atom",
      "custom-title",
      "swackets",
      "tree-view-open-files",
      "archive-view",
      "autoflow",
      "encoding-selector",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-objective-c",
      "language-ruby-on-rails",
      "language-toml",
      "line-ending-selector",
      "link",
      "metrics",
      "open-on-github",
      "package-generator",
      "spell-check",
      "styleguide",
      "welcome",
      "relative-numbers",
      "linter-sass-lint",
      "atom-alignment"
    ],
    "packagesWithKeymapsDisabled": [
      "indentation-indicator",
      "highlight-selected"
    ],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "vim-mode-plus": {
    "incrementalSearch": true,
    "stayOnTransformString": true,
    "stayOnYank": true,
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true,
    "wrapLeftRightMotion": true
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.9.0
aligner, v0.17.4
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-python, v1.0.1
aligner-scss, v1.1.0
atom-2048, v3.1.0
atom-beautify, v0.28.19
atom-material-syntax, v0.2.10
auto-detect-indentation, v0.4.2
autocomplete-html-entities, v0.1.0
color-picker, v2.0.14
emmet, v2.3.17
emmet-snippets-compatibility, v1.0.1
file-icons, v1.6.13
font-awesome-snippetset, v0.0.6
highlight-selected, v0.11.1
html-entities, v0.4.0
indentation-indicator, v0.6.0
jquery-snippets, v11.0.0
linter, v1.11.3
linter-csslint, v1.2.0
linter-jscs, v3.2.2
linter-less, v2.3.3
linter-pep8, v1.1.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
minimap-pigments, v0.1.7
parcel, v0.1.0
pigments, v0.19.5
remote-edit, v1.8.23
symbols-tree-view, v0.11.0
vim-mode-plus, v0.13.0

# Dev
No dev packages
```

**Comment by crshd** [comment]
Huh. Works fine with a clean config. I'll go hunting for it myself.

**Comment by crshd** [comment]
Found it. I set `.vim-mode-plus-input` to `display: none` in my `styles.less`. Turns out I shouldn't have done that.

**Comment by t9md** [comment]
Oh i see.

**Comment by admosity** [comment]
I am having this problem on atom version 1.4.3 and vim-mode-plus version 0.19.1.

**Comment by t9md** [comment]
This issue is already closed please open new issue with necessary information like platform version etc..
