### ISSUE TITLE
Uncaught Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by dcalhoun** [t9md/atom-vim-mode-plus#910]
Several fold commands throw errors.

### Steps to Reproduce
Execute any of the following.
- <kbd>z</kbd><kbd>M</kbd>
- <kbd>z</kbd><kbd>C</kbd>
- <kbd>z</kbd><kbd>O</kbd>
- <kbd>z</kbd><kbd>A</kbd> (with code previously folded)

### Environment
**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.9.0

### Stack Trace

Uncaught Error: Cannot find module 'semver'

```
At /Users/davidcalhoun/.atom/packages/vim-mode-plus/lib/operation-stack.js:160

Error: Cannot find module 'semver'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at atomVersionSatisfies (/packages/vim-mode-plus/lib/utils.js:1147:25)
    at getCodeFoldRowRanges (/packages/vim-mode-plus/lib/utils.js:347:7)
    at getFoldRangesWithIndent (/packages/vim-mode-plus/lib/utils.js:379:10)
    at getFoldInfoByKind (/packages/vim-mode-plus/lib/utils.js:400:36)
    at FoldAll.execute (/packages/vim-mode-plus/lib/misc-command.js:280:23)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.js:195:33)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.js:188:12)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.js:104:14)
    at /packages/vim-mode-plus/lib/base.js:389:45)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:19.6.0 vim-mode-plus:move-to-end-of-word (input.hidden-input)
     -0:19.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:19.3.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:17.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:17.5.0 vim-mode-plus:undo (input.hidden-input)
  2x -0:17 vim-mode-plus:move-down (input.hidden-input)
  2x -0:15.5.0 vim-mode-plus:move-up (input.hidden-input)
 14x -0:14.6.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:12.2.0 vim-mode-plus:move-up (input.hidden-input)
     -0:11.5.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
 20x -0:10.8.0 vim-mode-plus:move-down (input.hidden-input)
 33x -0:08.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:06.5.0 vim-mode-plus:fold-all (input.hidden-input)
     -0:02.8.0 vim-mode-plus:move-up (input.hidden-input)
  2x -0:02.6.0 vim-mode-plus:move-down (input.hidden-input)
     -0:02.0 vim-mode-plus:fold-all (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
atom-jest-snippets-standard 1.1.0 
atom-terminal-tab 0.2.2 
busy-signal 1.4.3 
ex-mode 0.18.0 
file-icons 2.1.12 
gist-it 0.9.2 
highlight-line 0.12.0 
ide-typescript 0.6.1 
intentions 1.1.5 
language-babel 2.75.1 
language-diff 0.7.0 
language-generic-config 1.4.0 
linter 2.2.0 
linter-js-standard 4.0.2 
linter-rubocop 2.2.0 
linter-stylelint 4.0.2 
linter-ui-default 1.6.10 
nerd-treeview 0.5.4 
one-dark-vivid-syntax 1.8.0 
pigments 0.40.2 
tab-foldername-index 3.2.1 
tabs-to-spaces 1.0.3 
tester 1.4.0 
tester-jest 1.1.8 
vim-mode-plus 1.9.0 
vim-mode-plus-jasmine-increase-focus 0.4.0 
Zen 0.18.0 
```

**Comment by t9md** [comment]
Sorry! and thanks for reporting.
This is CRITICAL mistake.
Fix and released as v1.9.1 now.
