### ISSUE TITLE
Uncaught TypeError: Cannot read property "NaN" of undefined

### ISSUE THREAD

**Issue by paradox460** [t9md/atom-vim-mode-plus#912]
1. Attempt to delete something via `dd`

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'NaN' of undefined

```
At /Users/jeff.sandberg/.atom/packages/vim-mode-plus/lib/operation-stack.js:160

TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:958:37)
    at TextEditorComponent.pixelLeftForRowAndColumn (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2344:35)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:204:46)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at /packages/pigments/lib/color-buffer-element.coffee:327:36)
    at HTMLElement.ColorBufferElement.updateDotDecorationsOffsets (/packages/pigments/lib/color-buffer-element.coffee:319:7)
    at /packages/pigments/lib/color-buffer-element.coffee:250:14
    at Array.forEach (native)
    at /packages/pigments/lib/color-buffer-element.coffee:249:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:781:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:780:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:763:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1002:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:956:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Delete.startMutation (/packages/vim-mode-plus/lib/operator.js:299:19)
    at Delete.execute (/packages/vim-mode-plus/lib/operator.js:310:10)
    at Delete.execute (/packages/vim-mode-plus/lib/operator.js:549:13)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.js:195:33)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.js:188:12)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.js:107:14)
    at /packages/vim-mode-plus/lib/base.js:389:45)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:602:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:460:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:54.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:50.1.0 intentions:highlight (input.hidden-input)
     -0:49.9.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:49.3.0 vim-mode-plus:delete (input.hidden-input)
  2x -0:30 tree-view:toggle (input.hidden-input)
     -0:28.1.0 settings-view:open (div.tool-panel.tree-view)
     -0:10.4.0 intentions:highlight (input.hidden-input)
     -0:10.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:02.5.0 intentions:highlight (input.hidden-input)
     -0:02.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:02.0 vim-mode-plus:delete (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
align-regexp 0.4.0 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-elixir 0.2.3 
atom-fuzzy-grep 0.16.0 
auto-indent 0.5.0 
autocomplete-bibtex 0.7.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 2.12.0 
blame 0.12.0 
busy-signal 1.4.3 
color-picker 2.2.5 
column-select 0.2.0 
css-comb 2.5.0 
ctags-status 1.3.7 
dash 1.7.1 
demo-mode 0.2.1 
docker 0.8.0 
dockerletion 0.2.0 
emmet 2.4.3 
escape-utils 0.5.3 
ex-mode 0.18.0 
file-icons 2.1.12 
fold-lines 0.2.2 
foldingtext-for-atom 0.9.2 
foldingtext-markdown 1.3.2 
gist 1.0.0 
git-blame 1.3.1 
git-diff-popup 0.1.8 
git-history 3.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
hard-wrap 1.1.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
indentation-indicator 1.1.0 
intentions 1.1.5 
json-path-finder 0.1.9 
jumpy 3.1.3 
language-babel 2.75.1 
language-cjsx 0.3.0 
language-confluence-wiki 0.2.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-dot 1.7.0 
language-earl-grey 0.10.0 
language-elixir 0.20.3 
language-fish-shell 1.0.5 
language-generic-config 1.4.0 
language-gfm-enhanced 0.92.0 
language-groovy 0.7.0 
language-haml 0.25.2 
language-latex 1.1.1 
language-log 1.9.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-pfm 0.82.0 
language-pug 0.0.21 
language-rspec 0.7.0 
language-slim 0.6.0 
language-vue 0.23.1 
latex-autocomplete 1.0.0 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
linter 2.2.0 
linter-chktex 1.3.1 
linter-coffeelint 1.3.1 
linter-docker 0.2.1 
linter-elixir-credo 1.1.0 
linter-eslint 8.3.2 
linter-haml 2.0.2 
linter-js-yaml 1.2.8 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-rubocop 2.2.0 
linter-slim 1.0.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
live-archive 0.1.15 
markdown-preview-enhanced 0.14.11 
markdown-table-editor 0.6.4 
markdown-writer 2.7.2 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
minimap-selection 4.5.0 
multi-wrap-guide 1.0.0 
narrow 0.52.0 
open-this 0.5.0 
pain-split 1.4.0 
pandoc 0.2.2 
pane-layout-plus 0.7.3 
pdf-view 0.59.0 
pigments 0.40.2 
polymorph 2.2.2 
preview 0.17.0 
project-manager 3.3.5 
quick-highlight 0.11.0 
rails-snippets 2.16.0 
rainbow-delimiters 1.3.0 
red-wavy-underline 0.3.3 
regex-railroad-diagram 0.19.4 
relative-numbers 0.8.0 
ror-refactor 0.3.1 
rspec-focus 0.2.1 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
ruby-block-converter 4.0.1 
sequential-number 0.5.0 
set-syntax 0.4.0 
simple-align 0.2.0 
snippet-generator 0.3.2 
sort-lines 0.17.0 
spaces-in-braces 0.1.0 
string-looper 0.1.2 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
tablr 1.8.3 
tabs-to-spaces 1.0.3 
tabular 0.1.0 
tabularize 0.2.5 
toggle-quotes 1.0.1 
tomorrow-ui 0.3.0 
transform 0.4.0 
tree-view-git-modified 0.7.3 
underline-trailing-whitespace 1.4.2 
vim-mode-plus 1.9.1 
vim-mode-plus-duplicate 0.2.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-move-selected-text 0.11.0 
vim-mode-plus-move-to-symbols 0.4.0 
white-cursor 0.7.0 
wordcount 2.10.4 
yard 0.3.1 
```

**Comment by paradox460** [comment]
It looks like this _may_ be related to the Pigments package

**Comment by t9md** [comment]
How often you see this issue, always you did dd?
If you disable pigments, you no longer see this issue?

**Comment by paradox460** [comment]
I think the issue may actually be related to https://github.com/atom/atom/issues/15827, as it appears that file's history got corrupted.

I force-closed atom and reopened the file and didn't have issues with it anymore.

**Comment by t9md** [comment]
OK, I'll close now, If you still encounter same issue, reopen this.
