### ISSUE TITLE
Uncaught Error: class 'InsertAfterEndOfLine' not found

### ISSUE THREAD

**Issue by jiantao** [t9md/atom-vim-mode-plus#924]
[Enter steps to reproduce:]

1. open any documents

2. type 'A' in normal mode

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.11.2

### Stack Trace

Uncaught Error: class 'InsertAfterEndOfLine' not found

```
At /home/jiantao/.atom/packages/vim-mode-plus/lib/base.js:353

Error: class 'InsertAfterEndOfLine' not found
    at Function.getClass (/packages/vim-mode-plus/lib/base.js:353:11)
    at getClass (/packages/vim-mode-plus/lib/base.js:395:44)
    at /packages/vim-mode-plus/lib/base.js:400:49)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
ex-mode 0.18.0 
vim-mode-plus 1.11.2 
```

**Comment by t9md** [comment]
Uninstall then reinstall vim-mode-plus solve issue?

**Comment by t9md** [comment]
I have no idea. close-to-re-evaluate.
