### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by bnord** [t9md/atom-vim-mode-plus#93]
[Enter steps to reproduce below:]

1. highlight/select all text.
2. attempt to delete all text with delete key.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.9.5
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/nord/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:43

TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:669:23)
    at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:596:35)
    at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2324:33)
    at InnerIndentation.Indentation.getRange (/Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:411:31)
    at InnerIndentation.Paragraph.selectParagraph (/Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:369:15)
    at /Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:378:10
    at Object._.times (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:1119:53)
    at /Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:377:9
    at InnerIndentation.TextObject.eachSelection (/Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:33:5)
    at InnerIndentation.Paragraph.select (/Users/nord/.atom/packages/vim-mode-plus/lib/text-object.coffee:376:6)
    at Select.Operator.selectTarget (/Users/nord/.atom/packages/vim-mode-plus/lib/operator.coffee:92:15)
    at Select.execute (/Users/nord/.atom/packages/vim-mode-plus/lib/operator.coffee:137:6)
    at OperationStack.process (/Users/nord/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:70:10)
    at OperationStack.run (/Users/nord/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:39:8)
    at run (/Users/nord/.atom/packages/vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/nord/.atom/packages/vim-mode-plus/lib/base.coffee:158:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:14.8.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:14.4.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  7x -0:14 core:select-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:12.8.0 core:move-left (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode)
  8x -0:12 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:10.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  2x -0:09.6.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  3x -0:08.6.0 core:move-left (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:07.4.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
  2x -0:06.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
  3x -0:05.4.0 core:backspace (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
     -0:04.6.0 core:move-down (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
     -0:03.9.0 core:select-all (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.insert-mode)
     -0:03.5.0 core:move-left (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode)
     -0:02.0 core:select-all (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.normal-mode)
     -0:00.9.0 vim-mode-plus:inner-indentation (atom-text-editor.editor.vim-mode.vim-mode-plus.is-focused.visual-mode)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  },
  "vim-mode-plus": {
    "useClipboardAsDefaultRegister": true,
    "useSmartcaseForSearch": true,
    "stayOnYank": true
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.7
github-utils, v0.8.0
indent-guide-ext, v0.2.1
minimap, v4.19.0
my-github-profile, v0.2.1
pigments, v0.19.5
python-tools, v0.6.7
term3, v0.19.2
terminal-plus, v0.14.5
vim-mode, v0.64.0
vim-mode-plus, v0.11.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
See #99.
