### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isReady' of undefined

### ISSUE THREAD

**Issue by shemerey** [t9md/atom-vim-mode-plus#948]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.17.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isReady' of undefined

```
At /Users/zork/.atom/packages/vim-mode-plus/lib/operation-stack.js:173

TypeError: Cannot read property 'isReady' of undefined
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.js:173:13)
    at MoveToMark.processOperation (/packages/vim-mode-plus/lib/base.js:102:34)
    at onConfirm (/packages/vim-mode-plus/lib/base.js:138:14)
    at CompositeDisposable.onDidSetInputChar.char (/packages/vim-mode-plus/lib/vim-state.js:609:9)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at VimState.emitDidSetInputChar (/packages/vim-mode-plus/lib/vim-state.js:203:44)
    at /packages/vim-mode-plus/lib/main.js:186:14)
    at HTMLElement.didDispatch (/packages/vim-mode-plus/lib/main.js:201:30)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:22.6.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:22.6.0 core:cancel (input.hidden-input)
     -0:20.9.0 vim-mode-plus:change-surround (input.hidden-input)
     -0:20.9.0 vim-mode-plus:move-to-mark-line (input.hidden-input)
     -0:19.7.0 vim-mode-plus:set-input-char-` (input.hidden-input)
     -0:16 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:15.9.0 vim-mode-plus:set-input-char-u (input.hidden-input)
     -0:14.7.0 vim-mode-plus:undo (input.hidden-input)
     -0:07.3.0 vim-mode-plus:change-surround (input.hidden-input)
     -0:07.3.0 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:06.4.0 editor:consolidate-selections (input.hidden-input)
     -0:06.4.0 core:cancel (input.hidden-input)
     -0:05.8.0 core:save (input.hidden-input)
     -0:04.1.0 vim-mode-plus:set-input-char-i (input.hidden-input)
     -0:03.3.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
busy-signal 1.4.3 
cmetr 0.0.0 
cursor-history 0.12.0 
go-debug 1.5.2 
go-plus 5.6.0 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
ide-go 0.4.0 
intentions 1.1.5 
keys-typed-tracker 2.1.1 
language-slim 1.0.0 
linter 2.2.0 
linter-ui-default 1.6.10 
project-manager 3.3.5 
script 3.17.3 
significant-other 0.4.0 
toggler 0.3.0 
vim-mode-plus 1.17.0 
wakatime 7.0.3 
```

**Comment by t9md** [comment]
Oh,, I might understand the cause.

Maybe this is similar to https://github.com/t9md/atom-vim-mode-plus/issues/922 ?

@shemerey Can you reproduce this 100%? then how?
From my understanding this issue is exist from very older version.

**Comment by shemerey** [comment]
I've tried to do something like cs'`, and then it hit me with an error, I've got it twice. but now can't find the right sequence to reproduce. Will add here if find out `how`

**Comment by t9md** [comment]
You keyboard require TWO keystrokes to type `'` or ``` ` ```?

**Comment by shemerey** [comment]
nope, it's regular macbook, USA keyboard layout, the only thing I have `caps lock` mapped to `esc` 
so can incidentally hit it,

**Comment by t9md** [comment]
OK, then I have no idea how to repro too.

**Comment by shemerey** [comment]
I'll update here if find out to way to reproduce. thx for your fast response and great work 👍

**Comment by t9md** [comment]
- The way vmp read input from user for `"`(register), ``` ` ```(mark), `'`(mark) is ugly, hacky.
- This is leftover when I tried to solve "`f` is slow" issue https://github.com/t9md/atom-vim-mode-plus/pull/448.
  - Recently, `f` is already back to non-hacky way to read user-input in https://github.com/t9md/atom-vim-mode-plus/pull/838.
- Still `m`, ``` ` ```, `'` use hacky way to read user-input via keymap, not via input-form.
- I can remove this hacky way completely, but we no longer can do following keymap.
  - keymap `m a` to `some-commands` and still user other `m`(e.g. `m b`, `m c`...) as `vmp:mark` command.
- This is Atom's keymap's limitation and I can accept this limitation since I don't have those keymap for now.

How do you think?

Refs: https://github.com/atom/atom-keymap/issues/130
