### ISSUE TITLE
Exception when binding mark to 'g'

### ISSUE THREAD

**Issue by wolfson109** [t9md/atom-vim-mode-plus#962]
Try to bind a mark in the editor to g by using 'm g' causes an exception to be thrown with the following stack trace:
TypeError: Cannot read property '0' of undefined
    at PartialKeyupMatcher.getMatches (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:42:105)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:375:91)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)

The exception is then thrown on every keystroke until atom is closed an reopened.

Marks seems to work fine for all other keys, just not g.

Atom: 1.20.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
vim-mode-plus: 1.16.0
OS: Ubuntu 14.04

**Comment by t9md** [comment]
Your atom editor is a bit old, can you reproduce iwith latest stable and beta?
It's 1.22 and 1.23.

**Comment by wolfson109** [comment]
I've tried with 1.22 and it works fine. Thanks.
