### ISSUE TITLE
Uncaught Error: Cannot find module 'change-case'

### ISSUE THREAD

**Issue by andyngo** [t9md/atom-vim-mode-plus#979]
[Enter steps to reproduce:]

1. Replace a character with the "R" key
2. Error notification should show up.
3. It's always reproduceable (both in the latest stable Atom and Atom Beta)

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.20.0

### Stack Trace

Uncaught Error: Cannot find module 'change-case'

```
At /Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/operation-stack.js:151

Error: Cannot find module 'change-case'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/operator-transform-string.js:3:20)
    at Object.<anonymous> (/Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/operator-transform-string.js:912:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Function.getClass (/Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/base.js:221:21)
    at OperationStack.run (/Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/operation-stack.js:79:45)
    at HTMLElement.<anonymous> (/Users/andyngo/Documents/Source Codes/atom-vim-mode-plus/lib/base.js:270:33)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:16 vim-mode-plus:replace-character (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.9 
atom-csscomb 3.0.0 
atom-handlebars 1.3.0 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
choose-pane 0.6.1 
csscomb 0.3.1 
custom-title 1.0.1 
editorconfig 2.2.2 
emmet 2.4.3 
file-type-icons 1.3.4 
gloom 0.6.4 
highlight-selected 0.13.1 
html2slim 0.5.0 
indent-guide-improved 1.4.13 
indentation-indicator 1.1.0 
intentions 1.1.5 
language-babel 2.79.0 
language-slim 1.0.0 
language-vue 0.23.1 
lines 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
material-palenight-syntax 1.5.7 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
narrow 0.53.2 
octocat-syntax 2.1.11 
paner 1.0.0 
pigments 0.40.2 
prettier-atom 0.41.0 
project-manager 3.3.5 
relative-numbers 0.8.0 
ruby-slim 0.2.0 
sync-settings 0.8.3 
teletype 0.2.3 
todo-show 2.1.0 
tree-view-git-status 1.4.0 
vim-mode-plus 1.20.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-selected-text 0.11.1 
```

**Comment by andyngo** [comment]
Apologies, NPM installed and it's working fine now.

**Comment by t9md** [comment]
You manually install vmp from github right? Since I've not yet published change-case using version.

**Comment by andyngo** [comment]
Yes I did. :)

**Comment by t9md** [comment]
understood. I thought I mistakenly released when I saw your issue subject!
