### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setInputEnabled' of null

### ISSUE THREAD

**Issue by bendavis78** [t9md/atom-vim-mode-plus#98]
1. Install [move-panes](https://atom.io/packages/move-panes) package
2. Move a tab from one pane to another

**Atom Version**: 1.3.2
**System**: linux 4.2.6-9ph
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setInputEnabled' of null

```
At /home/ben/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:83

TypeError: Cannot read property 'setInputEnabled' of null
    at ModeManager.activateNormalMode (/home/ben/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:83:29)
    at ModeManager.<anonymous> (/home/ben/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:70:27)
    at ModeManager.activate (/home/ben/.atom/packages/vim-mode-plus/lib/mode-manager.coffee:69:20)
    at VimState._results.push._this.(anonymous function) [as activate] (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/delegato/lib/delegator.js:67:61)
    at new VimState (/home/ben/.atom/packages/vim-mode-plus/lib/vim-state.coffee:59:8)
    at /home/ben/.atom/packages/vim-mode-plus/lib/main.coffee:33:22
    at /usr/share/atom/resources/app.asar/src/workspace.js:287:16
    at /usr/share/atom/resources/app.asar/src/workspace.js:352:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:375:27)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:359:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:344:20)
    at Object.module.exports.swapEditor (/home/ben/.atom/packages/move-panes/lib/move-panes.coffee:40:12)
    at Object.module.exports.move (/home/ben/.atom/packages/move-panes/lib/move-panes.coffee:35:8)
    at Object.module.exports.moveLeft (/home/ben/.atom/packages/move-panes/lib/move-panes.coffee:12:17)
    at atom-workspace.<anonymous> (/home/ben/.atom/packages/move-panes/lib/move-panes.coffee:5:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:18.2.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:17.8.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:16.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.5.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:11.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:09.4.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:08.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:08.4.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.9.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.2.0 vim-mode-plus:insert-below-with-newline (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.4.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:03.2.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:02.8.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:02.2.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:01.0 move-panes:move-left (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.9.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "linter-htmlhint",
      "linter-polymer",
      "one-tab",
      "polymer-snippets"
    ],
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false
  },
  "vim-mode-plus": {
    "useClipboardAsDefaultRegister": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
autocomplete-polymer, v0.2.4
browser-plus, v0.0.54
editorconfig, v1.2.2
gutter-shadow, v0.6.0
hidpi, v0.10.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-jshint, v1.2.1
minimize-panes, vundefined
move-panes, v0.2.0
move-status-items, v0.0.11
project-manager, v2.6.5
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
toggle-gutter, v0.2.2
vim-mode-plus, v0.11.0
wakatime, v5.0.2
workspaces, v0.0.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Can you reproduce it every time? or occasional issue?
You observed issue only when you use with move-panes package?
To fix that I want reproduce issue in my local env, but before blindly trying to reproduce issue, I need minimum condition you can reproduce this issue.

**Comment by geksilla** [comment]
Hi, @t9md, got same issue.
To reproduce this one install move-panes package.
Open some file.
Split buffer vertically or horizontally.
Perform move-pane action.
Error `Uncaught TypeError: Cannot read property 'setInputEnabled' of null` will be thrown.
Tab will be removed and not moved.
Workaround that works for me is to check for `component` [here](https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/mode-manager.coffee#L85) like:

```coffee
@editorElement.component?.setInputEnabled(false)
```

**Comment by t9md** [comment]
Thanks @geksilla for investigation and clear explanation!

**Comment by geksilla** [comment]
Thanks @t9md for quick response and release!
