### ISSUE TITLE
When searching with "/" -> Uncaught TypeError: Cannot read property 'uniq' of undefined

### ISSUE THREAD

**Issue by granteagon** [t9md/atom-vim-mode-plus#988]
# Check list

You have to check all before open issue.

- [ x ] Try with latest Atom and latest vim-mode-plus.
- [ x ] Pick descriptive and non-ambiguous subject
- [ x ] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).

This is a bug.

- [ x ] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.

Just a bug fix.  
- [ x ] Include real use case so that maintainer can understand "why" you need help.

In normal mode, type "/".  Enter search string and press "Enter".  Error shows.  

- [ x ] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

- [ x ] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

Not key binding issue.

The Error
============================

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'uniq' of undefined

```
At C:\Users\notactualbear\.atom\packages\vim-mode-plus\lib\search-history-manager.js:21

TypeError: Cannot read property 'uniq' of undefined
    at SearchHistoryManager.save (/packages/vim-mode-plus/lib/search-history-manager.js:21:58)
    at Search.moveCursor (/packages/vim-mode-plus/lib/motion-search.js:117:37)
    at Search.moveWithSaveJump (/packages/vim-mode-plus/lib/motion.js:75:12)
    at Search.execute (/packages/vim-mode-plus/lib/motion.js:89:16)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.js:193:33)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.js:186:12)
    at Search.processOperation (/packages/vim-mode-plus/lib/base.js:156:36)
    at Search.handleConfirmSearch (/packages/vim-mode-plus/lib/motion-search.js:241:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SearchInput.confirm (/packages/vim-mode-plus/lib/search-input.js:154:18)
    at /packages/vim-mode-plus/lib/search-input.js:60:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -8:55.1.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  2x -8:54.8.0 vim-mode-plus:move-down (input.hidden-input)
     -8:54.3.0 vim-mode-plus:delete (input.hidden-input)
  2x -8:54.2.0 vim-mode-plus:move-up (input.hidden-input)
     -8:53.7.0 vim-mode-plus:put-after (input.hidden-input)
     -8:53.1.0 intentions:highlight (input.hidden-input)
     -8:53 core:save (input.hidden-input)
     -0:52.3.0 vim-mode-plus:search (input.hidden-input)
  2x -0:50.8.0 core:backspace (input.hidden-input)
     -0:46.3.0 editor:consolidate-selections (input.hidden-input)
     -0:46.3.0 core:cancel (input.hidden-input)
     -0:46 vim-mode-plus:move-to-first-character-of-line-down (input.hidden-input)
     -0:44.6.0 vim-mode-plus:repeat-search (input.hidden-input)
     -0:43.5.0 vim-mode-plus:search (input.hidden-input)
     -0:40.5.0 core:confirm (input.hidden-input)
     -0:23.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.6 
atom-easy-jsdoc 4.12.4 
atom-import-cost 1.2.0 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
autocomplete-python 1.10.3 
blame 0.12.0 
busy-signal 1.4.3 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.76.4 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-pylint 2.1.0 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
project-plus 1.0.0 
python-indent 1.1.2 
python-tools 0.6.9 
relative-numbers 0.8.0 
split-diff 1.5.1 
Sublime-Style-Column-Selection 1.7.4 
teletype 0.1.2 
vim-mode-plus 1.15.0 
```

**Comment by t9md** [comment]
vmp version is too old, first upgrade it to latest.
I believe you can't reproduce it with latest version, if you can, please put steps how-to-repro-info here.
